//********************************************************************
//*    
//* Warning: This file was generated by ecore4CPP Generator
//*
//********************************************************************

#ifndef PSSM_SEMANTICS_STATEMACHINES_STATEMACHINECONFIGURATIONSTATEMACHINECONFIGURATIONIMPL_HPP
#define PSSM_SEMANTICS_STATEMACHINES_STATEMACHINECONFIGURATIONSTATEMACHINECONFIGURATIONIMPL_HPP

//*********************************
// generated Includes

// namespace macro header include
#include "PSSM/PSSM.hpp" 

// model includes
#include "../StateMachineConfiguration.hpp"

#include "PSSM/Semantics/StateMachines/impl/StateMachinesFactoryImpl.hpp"

#include "ecore/impl/EModelElementImpl.hpp"

//*********************************
namespace PSSM::Semantics::StateMachines 
{
	class PSSM_API StateMachineConfigurationImpl : virtual public ecore::EModelElementImpl,
virtual public StateMachineConfiguration 
	{
		public: 
			StateMachineConfigurationImpl(const StateMachineConfigurationImpl & obj);
			virtual std::shared_ptr<ecore::EObject> copy() const;
			StateMachineConfigurationImpl& operator=(StateMachineConfigurationImpl const&); 

		protected:
			friend class PSSM::Semantics::StateMachines::StateMachinesFactoryImpl;
			StateMachineConfigurationImpl();
			virtual std::shared_ptr<PSSM::Semantics::StateMachines::StateMachineConfiguration> getThisStateMachineConfigurationPtr() const;
			virtual void setThisStateMachineConfigurationPtr(std::weak_ptr<PSSM::Semantics::StateMachines::StateMachineConfiguration> thisStateMachineConfigurationPtr);

			//Additional constructors for the containments back reference
			StateMachineConfigurationImpl(std::weak_ptr<PSSM::Semantics::StateMachines::StateMachineExecution> par_execution);

		public:
			//destructor
			virtual ~StateMachineConfigurationImpl();
			
			//*********************************
			// Operations
			//*********************************
			virtual bool _register(const std::shared_ptr<PSSM::Semantics::StateMachines::StateActivation>& stateActivation) ;
			virtual bool add(const std::shared_ptr<PSSM::Semantics::StateMachines::VertexActivation>& activation) ;
			
			
			virtual std::shared_ptr<Bag<PSSM::Semantics::StateMachines::VertexActivation>> getVertexActivationsAtLevel(int level) ;
			virtual bool isActive(const std::shared_ptr<PSSM::Semantics::StateMachines::VertexActivation>& activation) ;
			virtual bool isStable() ;
			virtual bool remove(const std::shared_ptr<PSSM::Semantics::StateMachines::VertexActivation>& vertexActivation) ;
			virtual bool unregister(const std::shared_ptr<PSSM::Semantics::StateMachines::StateActivation>& stateActivation) ;
			
			//*********************************
			// Attribute Getters & Setters
			//*********************************
			
			//*********************************
			// Reference Getters & Setters
			//*********************************
			virtual std::weak_ptr<PSSM::Semantics::StateMachines::StateMachineExecution> getExecution() const ;
			virtual void setExecution(std::weak_ptr<PSSM::Semantics::StateMachines::StateMachineExecution>) ;
			virtual const std::shared_ptr<PSSM::Semantics::StateMachines::StateConfiguration>& getRootConfiguration() const ;
			virtual void setRootConfiguration(const std::shared_ptr<PSSM::Semantics::StateMachines::StateConfiguration>&) ;
			
			//*********************************
			// Union Reference Getters
			//*********************************
			
			//*********************************
			// Container Getter
			//*********************************
			virtual std::shared_ptr<ecore::EObject> eContainer() const ; 

			//*********************************
			// Persistence Functions
			//*********************************
			virtual void load(std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler) ;
			virtual void loadAttributes(std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler, std::map<std::string, std::string> attr_list);
			virtual void loadNode(std::string nodeName, std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler);
			virtual void resolveReferences(const int featureID, std::vector<std::shared_ptr<ecore::EObject>> references) ;
			virtual void save(std::shared_ptr<persistence::interfaces::XSaveHandler> saveHandler) const ;
			virtual void saveContent(std::shared_ptr<persistence::interfaces::XSaveHandler> saveHandler) const;

		protected:
			virtual const std::shared_ptr<ecore::EClass>& eStaticClass() const;

			//*********************************
			// EStructuralFeature Get/Set/IsSet
			//*********************************
			virtual std::shared_ptr<Any> eGet(int featureID, bool resolve, bool coreType) const ;
			virtual bool eSet(int featureID, const std::shared_ptr<Any>& newValue) ;
			virtual bool internalEIsSet(int featureID) const ;

			//*********************************
			// EOperation Invoke
			//*********************************
			virtual std::shared_ptr<Any> eInvoke(int operationID,const std::shared_ptr<Bag<Any>>& arguments) ;

		private:
			std::weak_ptr<PSSM::Semantics::StateMachines::StateMachineConfiguration> m_thisStateMachineConfigurationPtr;
	};
}
#endif /* end of include guard: PSSM_SEMANTICS_STATEMACHINES_STATEMACHINECONFIGURATIONSTATEMACHINECONFIGURATIONIMPL_HPP */
