# Info as well as warning messages can also be disabled from a specific level of depth (0-4)
# See examples below:
#	disableInfos(2) - disables all warnings with level >= 2
# 	disableWarnigs(1) - disables all warnings with level >= 1
# Providing a level of 0 to these calls is equivalent to a call to disable*All()
InfoLevel = 4
WarningLevel = 4
