#ifndef NEWMODEL_NEWMODEL_ACTIVITY_EXECUTION_HPP
#define NEWMODEL_NEWMODEL_ACTIVITY_EXECUTION_HPP

//********************************************************************
//*    
//* Warning: This file was generated by Mesapp Generator
//*
//********************************************************************


#include "fUML/Object.hpp"
#include "fUML/impl/ObjectImpl.hpp"
#include "uml/Element.hpp"
#include "NewModel activity.hpp"

namespace NewModel {

class NewModel activityExecution : public fUML::ObjectImpl 
{

public:
    //constructors
    NewModel activityExecution(NewModel activityExecution &obj);
    NewModel activityExecution(NewModel activity *);
 	NewModel activityExecution();
    //destructor
    virtual ~NewModel activityExecution();


    virtual ecore::EObject * copy();
	
	NewModel activity* getUmlValue();
	void setUmlValue(NewModel activity*);

protected:
	NewModel activity* m_umlValue;
};

}

#endif /* end of include guard: NEWMODEL_NEWMODEL ACTIVITY_EXECUTION_HPP */

