//********************************************************************
//*    	
//* Warning: This file was generated by MDE4CPP Generator
//*
//********************************************************************

#ifndef STANDARDPROFILE_METAMODEL_METAMODELIMPL_HPP
#define STANDARDPROFILE_METAMODEL_METAMODELIMPL_HPP

#include <functional>

//Model includes
#include "../Metamodel.hpp"
#include "uml/impl/StereotypeImpl.hpp"
#include "uml/Property.hpp"

class AnyObject;
typedef std::shared_ptr<AnyObject> Any;

namespace uml
{
	class Property;
}

//*********************************
namespace StandardProfile
{
	class MetamodelImpl : virtual public uml::StereotypeImpl, virtual public Metamodel
	{
		private:    
			MetamodelImpl(MetamodelImpl const&) = delete;
			MetamodelImpl& operator=(MetamodelImpl const&) = delete;

		protected:
			friend class StandardProfileFactoryImpl;
			//constructor
			MetamodelImpl();
			virtual std::shared_ptr<Metamodel> getThisMetamodelPtr();
			virtual void setThisMetamodelPtr(std::weak_ptr<Metamodel> thisMetamodelPtr);


		public:
			//destructor
			virtual ~MetamodelImpl();

			//*********************************
			// Operations
			//*********************************
			
			
			//*********************************
			// Attributes Getter Setter
			//*********************************
			virtual std::weak_ptr<uml::Model> getBase_Model() const ;
			virtual void setBase_Model (std::weak_ptr<uml::Model> _base_Model);
			

		protected:
			virtual std::shared_ptr<uml::Class> getMetaClass();

		public:
			//*********************************
			// Structural Feature Getter/Setter
			//*********************************
			virtual Any get(std::shared_ptr<uml::Property> _property) const ;
			virtual void set(std::shared_ptr<uml::Property> _property, Any value) ;
			virtual void unset(std::shared_ptr<uml::Property> _property) ;
			
		
		private:
			std::weak_ptr<Metamodel> m_thisMetamodelPtr;
			std::map<std::string,std::function<Any()>> m_getterMap;
			std::map<std::string,std::function<void(Any)>> m_setterMap;
			std::map<std::string,std::function<void()>> m_unsetterMap;
	};
}
#endif /* end of include guard: STANDARDPROFILE_METAMODEL_METAMODELIMPL_HPP */
