/*
 * MDE4CPP - Model Driven Engineering for C++
 *
 * Copyright (c) TU Ilmenau, Systems and Software Engineering Group
 * All rights reserved.
 *
 * MIT License
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this
 * software and associated documentation files (the "Software"), to deal in the Software
 * without restriction, including without limitation the rights to use, copy, modify, merge,
 * publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons
 * to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or
 * substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED *AS IS*, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
 * PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
 * FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

plugins {
//  id "org.barfuin.gradle.taskinfo" version "2.2.0"
}

import org.gradle.internal.os.OperatingSystem;

description 'MDE4CPP root project'

task generateAll() {
	group 'MDE4CPP'
	description 'Generate all models without compilation of generated source code'

	dependsOn 'generator:createAllGenerators'
	dependsOn 'src:generateEcoreModels' // includes OCL model & Parser
	dependsOn 'src:generateReflectionModels'
	dependsOn 'src:generateUMLProfiles'
	dependsOn 'src:common:FoundationalModelLibrary:generateFoundationalModelLibrary'
}

task compileCommonTools()
{
	group 'MDE4CPP'
	description 'Compile all used external tools'

	dependsOn 'src:deliverBasicInterfaces'
	dependsOn 'src:common:pluginFramework:compilePluginFramework'
	dependsOn 'src:common:persistence:compilePersistence'
}	

task compileAll() 
{
	group 'MDE4CPP'
	description 'Compile all generated source code of models without generating the models'

	dependsOn 'src:compileEcoreModels'
	dependsOn 'src:compileReflectionModels'
	dependsOn 'src:compileUMLProfiles'
	dependsOn 'src:compileOCLAll'

	dependsOn 'src:common:FoundationalModelLibrary:compileFoundationalModelLibrary'	
}

task buildAll() 
{
	group 'MDE4CPP'
	description 'build generators and all models'
	dependsOn 'compileCommonTools'
	dependsOn 'generateAll'
	dependsOn 'compileAll'
	dependsOn 'src:buildOCLAll'

	tasks.getByPath('compileCommonTools').mustRunAfter tasks.getByPath('generateAll')	
	tasks.getByPath('compileAll').mustRunAfter tasks.getByPath('compileCommonTools')
	tasks.getByPath('src:buildOCLAll').mustRunAfter tasks.getByPath('generateAll')
}


task installationInstruction() {
	group 'MDE4CPP'

	description	'installation instruction'

	def instructionMessage = '' +
	'##############################################################################\n' +
	'#                    Installation instruction for MDE4CPP                    #\n' +
	'##############################################################################\n' +
	'\n' +
	'Welcome to MDE4CPP framework!\n' +
	'To start the work with MDE4CPP, you have to configure the environment settings.\n' +
	'A pattern is prepared for it:\n' +
	'- for Windows systems: setenv.bat.default\n' +
	'- for Unix systems: setenv.default.\n' +
	'Copy the file and remove the extension \'default\' first.\n' +
	'Open this file and configure the variables afterwards.\n' +
	'Run the file in a console. Note, that the environment is set inside the console\n' +
	'and has to be redone at each season start\n' +
	'More information see https://github.com/MDE4CPP/MDE4CPP\n' +
	'\n'

	/*def files = file('$projectDir').listFiles(new FileFilter() {
	public boolean accept(File pathname) {
	def extension = '.sh'
	if (System.properties['os.name'].toLowerCase().contains('windows')) {
	extension = '.bat'
	}

	return pathname.getName().endsWith(extension);
	}
	})*/

	/*if (files.length == 0) {
	println instructionMessage
	} else {*/
	doFirst {
		println instructionMessage
	}
//}
}

task setEnvironment(type:Exec){
	workingDir System.getenv('MDE4CPP_HOME')
	if (OperatingSystem.current().isWindows()) {
			// MS Windows
			commandLine 'cmd', '/c', 'setenv.bat'
		} else if (OperatingSystem.current().isLinux()) {
			// GNU/Linux
			commandLine 'sh', '-c', '. ./setenv'
		} else if (OperatingSystem.current().isMacOsX()){
			// Apple macOS
			commandLine "bash", "-c", "source setenv"
		} else {
			// OS not supported yet
			throw new GradleException('OS ' + System.getProperty('os.name') + ' is not supported yet')
		}
	doLast {
		println 'Environment variable have been set.'
	}
}

task startModelingEclipse(type:Exec){
	group 'Utilities'
	description 'sets and checks the environment variables and starts the Eclipse instance (EMF) specified in the setenv file'

	dependsOn 'checkEnvironment'
	workingDir System.getenv('MDE4CPP_ECLIPSE_HOME') //No need to check it here, if it does not exist checkEnvironment will fail with an exception

	if(OperatingSystem.current().isWindows()){
		// MS Windows
		commandLine 'cmd', '/c', 'eclipse.exe'
	} else if(OperatingSystem.current().isLinux()){
		// GNU/Linux
		commandLine './eclipse'
	} else if(OperatingSystem.current().isMacOsX()){
		// Apple macOS
		commandLine '../MacOS/eclipse'
	} else {
		// OS not supported yet
		throw new GradleException('OS ' + System.getProperty('os.name') + ' is not supported yet')
	}
}

/**
 * Deliver Boost headers for PluginAPI (Crow dependency).
 * 1. If application/include/boost already has headers, skip.
 * 2. If BOOST_ROOT is set, copy from there to application/include/boost.
 * 3. Else download Boost 1.82.0 and extract the boost/ folder to application/include/boost.
 */
task deliverBoostLibray {
	group 'pluginAPI'
	description 'Deliver Boost headers to application/include/boost for Crow/PluginAPI'

	def boostIncludeDir = file("${rootDir}/application/include/boost")
	def requiredHeader = file("${rootDir}/application/include/boost/algorithm/string/predicate.hpp")
	def requiredIpp = file("${rootDir}/application/include/boost/asio/execution/impl/receiver_invocation_error.ipp")
	def toolsDir = file("${rootDir}/application/tools")
	def boostZip = file("${toolsDir}/boost_1_82_0.zip")
	def boostUrl = "https://archives.boost.io/release/1.82.0/source/boost_1_82_0.zip"

	outputs.dir(boostIncludeDir)
	outputs.upToDateWhen { requiredHeader.exists() && requiredIpp.exists() }

	doFirst {
		if (requiredHeader.exists() && requiredIpp.exists()) {
			return
		}
		def boostRoot = System.getenv('BOOST_ROOT')
		if (boostRoot != null && !boostRoot.isEmpty()) {
			def boostSrc = file("${boostRoot}/boost")
			if (!boostSrc.exists() || !boostSrc.isDirectory()) {
				throw new GradleException("BOOST_ROOT (${boostRoot}) must contain a 'boost' subdirectory.")
			}
			copy {
				from(boostSrc)
				into(boostIncludeDir)
				include('**/*.hpp')
				include('**/*.h')
				include('**/*.ipp')
			}
			println "Delivered Boost headers from ${boostRoot} to application/include/boost"
			return
		}
		// Download Boost and extract boost/ into application/include
		toolsDir.mkdirs()
		if (!boostZip.exists()) {
			println "Downloading Boost 1.82.0 (required for PluginAPI)..."
			boostZip.withOutputStream { os ->
				new URL(boostUrl).withInputStream { is -> os << is }
			}
		}
		println "Extracting Boost headers to application/include/boost..."
		copy {
			from(zipTree(boostZip))
			into(file("${rootDir}/application/include"))
			include("boost_1_82_0/boost/**/*.hpp")
			include("boost_1_82_0/boost/**/*.h")
			include("boost_1_82_0/boost/**/*.ipp")
			eachFile { fcd -> fcd.path = fcd.path.replaceFirst("boost_1_82_0/", "") }
			includeEmptyDirs = false
		}
		println "Boost headers delivered to application/include/boost"
	}
}

task startCPPEclipse(type:Exec){
	group 'Utilities'
	description 'sets and checks the environment variables and starts the C++ IDE specified in the setenv file'

	dependsOn 'checkEnvironment'

		if(System.getenv('CPP_IDE_EXECUTABLE') == null)
		{
			println 'The required variable CPP_IDE_EXECUTABLE has not been set in your setEnv file.'
		}
		else
		{
			if (System.getProperty('os.name').toLowerCase(Locale.ROOT).contains('windows'))
			{
				//on windows:
				 Thread.start {
				commandLine 'cmd', '/c', (System.getenv('CPP_IDE_EXECUTABLE') + '/eclipse.exe')
				}
			}
			else
			{
				//on linux
				commandLine 'bash' , System.getenv('CPP_IDE_EXECUTABLE')+'/eclipse'
			}
		}
}

task checkEnvironment(){
	dependsOn 'setEnvironment'
	group 'Utilities'
	description 'Check that all required variables defined in the setenv file are set and can be found'

	ext.checkPath = { path ->
		if(path == null || ! new File(path).exists()){
			return false;
		}
		return true;
	}

	ext.checkVariableExists = { variable_name, should_fail ->
		println ''
		def my_var = System.getenv(variable_name);
		if(my_var == null)
		{
			if(should_fail){
				throw new GradleException(variable_name + ' variable has not been set')
			}
			else
			{
				println printColor('Warning:', 'yellow') +  ' variable not set: ' + variable_name;
				return false;
			}
		}
		print variable_name + ': ' + my_var
		return true;
	}

	ext.printColor = { text, color ->
		def fg;
		def finalString;
		def bg = 49;
		switch(color) {
			case "red":
			fg = 31;
			break
			case "green":
			fg = 32;
			break

			case "yellow":
			fg = 33;
			break

			default:
			throw new GradleException('color "'+color+'" not defined')
			break
		}
		def style = "${(char)27}[$fg;$bg"+"m"
		finalString = style + text
		//Restore the original color:
		finalString += "${(char)27}[39;49m"
		return finalString;
	}

	ext.checkAndPrintPath = { path ->
		println ''
		path = path.replace('\\', '/')
		if(! checkPath(path)){
			println path + printColor(' <- Warning! Path element not found!', 'yellow');
			return
		}
		println path + printColor(' (exists)', 'green');
	}

	ext.checkCompilerIncludes = {
		println '\n\n---------------------------'
		println 'YOUR COMPILER INCLUDE PATHS'
		println '---------------------------'
		println 'you can ignore these if you are not using Eclipse as your C++ IDE'

		checkVariableExists('COMPILER_DELIVERY_NAME', false);
		checkVariableExists('COMPILER_VERSION', false);

		def home = System.getenv('COMPILER_HOME');
		def delivery = System.getenv('COMPILER_DELIVERY_NAME');
		def version = System.getenv('COMPILER_VERSION');

		println ''
		checkAndPrintPath(home + "include")
		checkAndPrintPath(home + "lib/gcc/" + delivery + "/" + version + "/include/c++")
		checkAndPrintPath(home + "lib/gcc/" + delivery + "/" + version + "/include/c++/backward")
		checkAndPrintPath(home + "lib/gcc/" + delivery + "/" + version + "/include/c++/" + delivery)
		checkAndPrintPath(home + "lib/gcc/" + delivery + "/" + version + "/include-fixed")
		checkAndPrintPath(home + "lib/gcc/" + delivery + "/" + version + "/include")
	}

	ext.checkMyVariablePath = { variable_name, should_fail ->
		checkVariableExists(variable_name, should_fail)
		if(! checkPath(System.getenv(variable_name))){
			if(should_fail){
				throw new GradleException('Path for variable ' + variable_name + ' cannot be found.' + System.getenv(variable_name))
			}
			return;
		}
		println printColor(' (exists)', 'green');
	}

	doFirst{
		println '------------------'
		println 'YOUR PATH VARIABLE'
		println '------------------'

		println 'PATH: ' + System.getenv('PATH')

    def os_separator = OperatingSystem.current().isWindows() ? ';' : ':'
		def path_elements = System.getenv('PATH').split(os_separator)

		println '\nAnalyzing all path elements...'
		path_elements.each{el ->
			if(! checkPath(el))
			{
				println 'PATH contains an invalid element: ' + el;
			}
			else{
				println '\t' + el + printColor(' (exists)', 'green');
			}
		}

		println '\n------------------------------'
		println 'YOUR ENV VARIABLES WITH A PATH'
		println '------------------------------'

		checkMyVariablePath('MDE4CPP_HOME', true)
		checkMyVariablePath('MDE4CPP_ECLIPSE_HOME', true)

		checkMyVariablePath('COMPILER_HOME', false)
		checkMyVariablePath('CMAKE_HOME', false)
		checkMyVariablePath('JAVA_HOME', false)
		checkMyVariablePath('CPP_IDE_EXECUTABLE', false)

		println '\n---------------------------------------'
		println 'YOUR ENV VARIABLES WITH A CONFIGURATION'
		println '---------------------------------------'

		checkVariableExists('GRADLE_OPTS', false);
		checkVariableExists('ORG_GRADLE_PROJECT_WORKER', false);
		checkVariableExists('ORG_GRADLE_PROJECT_RELEASE', false);
		checkVariableExists('ORG_GRADLE_PROJECT_DEBUG', false);
		checkVariableExists('ORG_GRADLE_PROJECT_DEBUG_MESSAGE_FUML', false);
		checkVariableExists('COMPILER_DELIVERY_NAME', false);
		checkVariableExists('COMPILER_VERSION', false);

		checkCompilerIncludes();
	}
}

task runInstallScripts()
{		
//private 	group 'MDE4CPP'
	description 'Run the installation scripts for MDE4CPP. This will set the environment variables and check them. It is recommended to run this task only once, then set the environment variables permanently in your system settings.'

	def installScripts = [
		//	[{script name},[{environment Variable}, {value}]]
		['installJava',
			['MDE4CPP_JAVA_VERSION', '21']
		],
		['installCompiler',
			['MDE4CPP_COMPILER_VERSION', '13.2.0']
		],
		['installEclipse',
			['MDE4CPP_ECLIPSE_VERSION',	'2025-09'],
			['MDE4CPP_ECLIPSE_MILESTONE', 'R'],
			['MDE4CPP_ECLIPSE_ACCELEO_VERSION', '3.7'],
			['MDE4CPP_ECLIPSE_SIRIUS_VERSION', '7.4.11'],
			['MDE4CPP_ECLIPSE_SIRIUS_ECLIPSE_VERSION', '2023-03']
		],
		['installCMake',
			['MDE4CPP_CMAKE_VERSION', '4.3'],
			['MDE4CPP_CMAKE_BUILD_VERSION', '1']
		],
	]

	def tool = ''
	def command = ''
	def extension = ''
	def scriptPath = ''
	def envSetCommand = ''
	def envValuePrefix = ''
	def envValueSuffix = ''

	// workingDir System.getenv('MDE4CPP_HOME')
	if (OperatingSystem.current().isWindows()) 
	{
		// MS Windows
		tool = 'cmd'
		command = '/C'
		extension = '.bat'
		scriptPath = 'Windows'
		envSetCommand = 'set'
	} 
	else if (OperatingSystem.current().isLinux()) 
	{
		// GNU/Linux
		tool = '/bin/sh'
		command = '-c'
		extension = '.sh'
		scriptPath = 'Linux'
		envSetCommand = 'export'
		envValuePrefix = '"'
		envValueSuffix = '"'
	}
	else if (OperatingSystem.current().isMacOsX())
	{
		// Apple macOS
		tool = 'bash'
		command = '-c'
		extension = '.sh'
		scriptPath = 'MacOS'
		envSetCommand = 'export'
		envValuePrefix = '"'
		envValueSuffix = '"'
	}
	else 
	{
		// OS not supported yet
		throw new GradleException('OS ' + System.getProperty('os.name') + ' is not supported yet')
	}
	doLast {
		println 'Running installation scripts...'
		println 'This may take a while, please be patient.'
		
		installScripts.each {scripts ->
			exec
			{
				def envAssignments = scripts[1..-1].collect { envVar ->
					environment(envVar[0], envVar[1])
					def envValue = "${envValuePrefix}${envVar[1]}${envValueSuffix}"
					return "${envSetCommand} ${envVar[0]}=${envValue}"
				}
				def scriptCommand = '.' + File.separator + 'scripts' + File.separator + scriptPath + File.separator + scripts[0] + extension
				def fullCommand = envAssignments.join(' && ') + ' && ' + scriptCommand
				println 'Running: ' + scripts[0] 
				commandLine = [tool, command, fullCommand]
			}
			//println 'Finished:' + scripts [0]
		}
	}	
}	

// Root wrapper for the included gradlePlugins composite build task.
task publishMDE4CPPPluginsToMavenLocal {
	group 'base'
	description 'Publish MDE4CPP gradle plugins from the gradlePlugins composite build to mavenLocal'
	dependsOn gradle.includedBuild('gradlePlugins').task(':publishMDE4CPPPluginsToMavenLocal')
}

task install{
	group 'MDE4CPP'
	description 'Install MDE4CPP by setting the environment variables and checking them'

	dependsOn 'runInstallScripts'
 	dependsOn 'publishMDE4CPPPluginsToMavenLocal'

//	dependsOn 'checkEnvironment'
	
// install Plugins
// install tools (xerces, antlr , crow, boost ...)

//	tasks.getByPath('checkEnvironment').mustRunAfter tasks.getByPath('runInstallScripts')	
}

//EOF
