//********************************************************************
//*    
//* Warning: This file was generated by ecore4CPP Generator
//*
//********************************************************************

#ifndef LIBRARYMODEL_ECORE_AUTHORAUTHORIMPL_HPP
#define LIBRARYMODEL_ECORE_AUTHORAUTHORIMPL_HPP

#ifdef NDEBUG
    #define DEBUG_MESSAGE(a) /**/
#else
    #define DEBUG_MESSAGE(a) a
#endif

#ifdef ACTIVITY_DEBUG_ON
    #define ACT_DEBUG(a) a
#else
    #define ACT_DEBUG(a) /**/
#endif

//#include "util/ProfileCallCount.hpp"

//*********************************
// generated Includes

//Model includes
#include "../Author.hpp"

#include "libraryModel_ecore/impl/NamedElementImpl.hpp"



//*********************************
namespace libraryModel_ecore 
{
	class AuthorImpl :virtual public NamedElementImpl, virtual public Author 
	{
		public: 
			AuthorImpl(const AuthorImpl & obj);
			virtual std::shared_ptr<ecore::EObject> copy() const;

		private:    
			AuthorImpl& operator=(AuthorImpl const&) = delete;

		protected:
			friend class LibraryModel_ecoreFactoryImpl;
			AuthorImpl();



		public:
			//destructor
			virtual ~AuthorImpl();
			
			//*********************************
			// Operations
			//*********************************
			
			
			//*********************************
			// Attributes Getter Setter
			//*********************************
			
			
			//*********************************
			// Reference
			//*********************************
							
			
			//*********************************
			// Union Getter
			//*********************************
			 
			 
			//*********************************
			// Structural Feature Getter/Setter
			//*********************************
			
			virtual boost::any eGet(int featureID, bool resolve, bool coreType) const ;
			virtual void eSet(int featureID, boost::any newValue) ;

			virtual std::shared_ptr<ecore::EObject> eContainer() const ; 
			
		protected:
			virtual std::shared_ptr<ecore::EClass> eStaticClass() const;
	};
}
#endif /* end of include guard: LIBRARYMODEL_ECORE_AUTHORAUTHORIMPL_HPP */

