//********************************************************************
//*    
//* Warning: This file was generated by ecore4CPP Generator
//*
//********************************************************************

#ifndef ECORE_EOBJECT_HPP
#define ECORE_EOBJECT_HPP

#ifdef NDEBUG
    #define DEBUG_MESSAGE(a) /**/
#else
    #define DEBUG_MESSAGE(a) a
#endif

#include <string>
#include <map>
#include <vector>
#include "boost/any.hpp"

//*********************************
// generated Includes

//Forward Declaration for used types
namespace ecore 
{
	class EClass;
}

namespace ecore 
{
	class EObject;
}

namespace ecore 
{
	class EOperation;
}

namespace ecore 
{
	class EReference;
}

namespace ecore 
{
	class EStructuralFeature;
}

// base class includes

// enum includes


//*********************************
namespace ecore 
{
	/*!
	 */
	class EObject	{
		public:
 			EObject(const EObject &) {}
			EObject& operator=(EObject const&) = delete;
	
		protected:
			EObject(){}

		public:
			virtual ecore::EObject* copy() const = 0;

			//destructor
			virtual ~EObject() {}

			//*********************************
			// Operations
			//*********************************
			/*!
			 */ 
			virtual ecore::EClass *  eClass()  const  = 0;
			
			/*!
			 */ 
			virtual bool eIsProxy()  const  = 0;
			
			/*!
			 */ 
			virtual int eResource()  const  = 0;
			
			/*!
			 */ 
			virtual ecore::EStructuralFeature *  eContainingFeature()  const  = 0;
			
			/*!
			 */ 
			virtual ecore::EReference *  eContainmentFeature()  const  = 0;
			
			/*!
			 */ 
			virtual std::vector <   ecore::EObject *  > * eContents()  const  = 0;
			
			/*!
			 */ 
			virtual std::vector <   ecore::EObject *  > * eAllContents()  const  = 0;
			
			/*!
			 */ 
			virtual std::vector <   ecore::EObject *  > * eCrossReferences()  const  = 0;
			
			/*!
			 */ 
			virtual boost::any eGet(ecore::EStructuralFeature *  feature)  const  = 0;
			
			/*!
			 */ 
			virtual boost::any eGet(ecore::EStructuralFeature *  feature,bool resolve)  const  = 0;
			
			/*!
			 */ 
			virtual void eSet(ecore::EStructuralFeature *  feature,boost::any newValue)  const  = 0;
			
			/*!
			 */ 
			virtual bool eIsSet(ecore::EStructuralFeature *  feature)  const  = 0;
			
			/*!
			 */ 
			virtual void eUnset(ecore::EStructuralFeature *  feature)  const  = 0;
			
			/*!
			 */ 
			virtual boost::any eInvoke(ecore::EOperation *  operation,std::vector <   boost::any > * arguments)  const  = 0;
			
			
			//*********************************
			// Attributes Getter Setter
			//*********************************
			
			//*********************************
			// Reference
			//*********************************
			/*!
			 */
			virtual ecore::EObject *  eContainer() const = 0;
			
			/*!
			 */
			virtual void setContainer(ecore::EObject *  _eContainer) = 0;
			
			

		protected:
			//*********************************
			// Attribute Members
			//*********************************
			
			
			//*********************************
			// Reference Members
			//*********************************
			/*!
			 */
			ecore::EObject *  m_eContainer =  nullptr ;
			

		public:
			//*********************************
			// Union Getter
			//*********************************
			 
	};

}
#endif /* end of include guard: ECORE_EOBJECT_HPP */

