//********************************************************************
//*    
//* Warning: This file was generated by ecore4CPP Generator
//*
//********************************************************************

#ifndef PSCS_SEMANTICS_COMMONBEHAVIORFACTORYIMPL_HPP
#define PSCS_SEMANTICS_COMMONBEHAVIORFACTORYIMPL_HPP

// namespace macro header include
#include "PSCS/PSCS.hpp"

#include "ecore/impl/EFactoryImpl.hpp"

#include "PSCS/Semantics/CommonBehavior/CommonBehaviorFactory.hpp"

namespace CommonBehavior 
{	class CS_EventOccurrence;
}

namespace PSCS::Semantics::CommonBehavior 
{
	class PSCS_API CommonBehaviorFactoryImpl : virtual public ecore::EFactoryImpl , virtual public CommonBehaviorFactory 
	{
		private:    
			CommonBehaviorFactoryImpl(CommonBehaviorFactoryImpl const&) = delete;
			CommonBehaviorFactoryImpl& operator=(CommonBehaviorFactoryImpl const&) = delete;

		protected:
			friend class CommonBehaviorFactory;
			// Constructor
			CommonBehaviorFactoryImpl();

		public:
			virtual ~CommonBehaviorFactoryImpl();
			virtual std::shared_ptr<ecore::EObject> create(std::string _className,  std::shared_ptr<ecore::EObject> container=nullptr, const int referenceID = -1) const;
			virtual std::shared_ptr<ecore::EObject> create(const int classID,  std::shared_ptr<ecore::EObject> container = nullptr, const int referenceID = -1) const;
			virtual std::shared_ptr<ecore::EObject> create(std::shared_ptr<ecore::EClass> _class, std::shared_ptr<EObject> _container=nullptr, const int referenceID = -1) const;

			//Creator functions
			 virtual std::shared_ptr<PSCS::Semantics::CommonBehavior::CS_EventOccurrence> createCS_EventOccurrence(const int metaElementID = CommonBehaviorPackage::CS_EVENTOCCURRENCE_CLASS) const ;
			 //Add as contained object
			 virtual std::shared_ptr<PSCS::Semantics::CommonBehavior::CS_EventOccurrence> createCS_EventOccurrence_as_eventPool_in_ObjectActivation(std::shared_ptr<fUML::Semantics::CommonBehavior::ObjectActivation> par_ObjectActivation, const int metaElementID = CommonBehaviorPackage::CS_EVENTOCCURRENCE_CLASS) const ;
			 

		private:
			static CommonBehaviorFactory* create();
            std::map<std::string,int> m_idMap;
	};
}
#endif /* end of include guard: PSCS_SEMANTICS_COMMONBEHAVIORFACTORYIMPL_HPP */
