
include:
  - compose/setup.yml
  - compose/infrastructure.yml
  - compose/generators.yml
  - compose/core.yml
  - compose/fuml.yml
  - compose/ocl.yml
  - compose/reflection.yml
  - compose/profiles.yml
  - compose/application.yml


volumes:
  eclipse_data:
  gradle_cache:
