/*
 * MDE4CPP - Model Driven Engineering for C++
 *
 * Copyright (c) TU Ilmenau, Systems and Software Engineering Group
 * All rights reserved.
 *
 * MIT License
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this
 * software and associated documentation files (the "Software"), to deal in the Software
 * without restriction, including without limitation the rights to use, copy, modify, merge,
 * publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons
 * to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or
 * substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED *AS IS*, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
 * PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
 * FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */
plugins{
	id "tui.sse.mde4cpp.MDE4CPPGenerate" version "0.6"	
}

description 'Example collection'

import org.gradle.internal.os.OperatingSystem;

// use MDE4CPP Generator Task as generateModel
task generateModel(type: tui.sse.mde4cpp.MDE4CPPGenerate) {
	description 'generate C++ code of ecore.ecore model ecore'		
}

//########################   UML   ########################

def allUMLExamples = 
[
//	[{project directory}, {task name}]
	['./UMLExample/', 'compileUMLExample']
]

def allUMLModelExamples = 
[
//	[{Model project directory}, {Model name}, {taskName}]
	['./UMLModelExample/', 'LibraryModel_uml', 'LibraryModel_uml']
]

def allUMLTestSuiteModels =
[
//	[{Model project directory}, {Model name}, {taskName}]
	 ['./TestSuite/copyTestUML/', 'copyTestUML', 'CopyTestUML']
	,['./TestSuite/subsetUnion/', 'simpleUML', 'SimpleUML']	
]

task compileUMLExamples() {
	group 'Examples'
	description 'compile UML examples.'	
	
	doLast
	{
		def tool = '/bin/sh'
		def command = '-c'
		
		if (System.properties['os.name'].toLowerCase().contains('windows')) {
			tool = 'cmd'
			command = '/C'
		}
		
		allUMLExamples.each { taskVar ->
		// taskVar[0] = task project root directoy, taskVar[1] = task name
			exec
			{
				workingDir = file("${taskVar[0]}")
				commandLine = [tool, command, 'gradlew ' + taskVar[1]]
			}
		}
	}
}

task generateUMLModelExamples() {
	group 'Examples'
	description 'generate UML Model Examples'	
	
	dependsOn getRootProject().getTasksByName('createAllGenerators', true)
	
	allUMLModelExamples.each { model ->
		def buildModelFile = file("${model[0]}/model/build.gradle")
		def buildSrcFile = file("${model[0]}/src_gen/build.gradle")
		if(!(buildModelFile.exists() && buildSrcFile.exists()))
		{
			def generateTask = getRootProject().tasks.findByPath(':generateModel')
			if (generateTask) 
			{	
				dependsOn generateTask.configure
				{
					modelFilePath = file("${model[0]}/model/${model[1]}.uml")
				}
				dependsOn generateTask
			}	
			else
			{
				println "No generateModel task found in example project for model: " + model[1]
			}
		}
		else
		{		
			def projectPath = model[0].replace('./', '').replaceAll('/$', '')
			def targetProject = findProject(projectPath)			
			if (targetProject != null) 
			{
				dependsOn targetProject.tasks.getByName("generate${model[2]}")
			}
			else
			{
				println "No project found for model: " + projectPath + ":generate${model[2]}"
			}
		}
	}
}

task compileUMLModelExamples() {
	group 'Examples'
	description 'compile applications for UML Model Examples'	

	doLast
	{
		def tool = '/bin/sh'
		def command = '-c'
		
		if (System.properties['os.name'].toLowerCase().contains('windows')) {
			tool = 'cmd'
			command = '/C'
		}
		
		allUMLModelExamples.each { model ->
		// model[0] = model project root directoy, model[1] = model name
			exec
			{
				workingDir = file("${model[0]}")
				commandLine = [tool, command, 'gradlew compileApplicationFor' + model[1]]
			}
		}
	}
}

task buildUMLModelExamples() 
{
	group 'Examples'
	description 'generate and compile applications for UML Model Examples'

	def tasks = [
		generateUMLModelExamples,
		compileUMLModelExamples
	]
	
	for (int i = 0; i < tasks.size() - 1; i++) {
        tasks[i + 1].mustRunAfter(tasks[i])
    }
    
    dependsOn(tasks)
}

task generateUMLTestSuite() {
	group 'Tests'
	description 'generate test suite for UMLExamples'	
	
	dependsOn getRootProject().getTasksByName('createAllGenerators', true)

	allUMLTestSuiteModels.each { model ->
		def buildModelFile = file("${model[0]}/model/build.gradle")
		def buildSrcFile = file("${model[0]}/src_gen/build.gradle")
		if(!(buildModelFile.exists() && buildSrcFile.exists()))
		{
			def generateTask = getRootProject().tasks.findByPath(':generateModel')
			if (generateTask) 
			{	
				dependsOn generateTask.configure
				{
					modelFilePath = file("${model[0]}/model/${model[1]}.uml")
				}
				dependsOn generateTask
			}	
			else
			{
				println "No generateModel task found in example project for model: " + model[1]
			}
		}
		else
		{		
			def projectPath = model[0].replace('./', '').replaceAll('/$', '')
			def targetProject = findProject(projectPath)			
			if (targetProject != null) 
			{
				dependsOn targetProject.tasks.getByName("generate${model[2]}")
			}
			else
			{
				println "No project found for model: " + projectPath + ":generate${model[2]}"
			}
		}
	}
}

task compileUMLTestSuite() {
	group 'Tests'
	description 'compile applications for UMLExamples test suite'	

	doLast
	{
		def tool = '/bin/sh'
		def command = '-c'
		
		if (System.properties['os.name'].toLowerCase().contains('windows')) {
			tool = 'cmd'
			command = '/C'
		}
		
		allUMLTestSuiteModels.each { model ->
		// model[0] = model project root directoy, model[1] = model name
			exec
			{
				workingDir = file("${model[0]}")
				commandLine = [tool, command, 'gradlew compileApplicationFor' + model[1]]
			}
		}
	}
}

task buildUMLTestSuite() 
{
	group 'Tests'
	description 'generate and compile applications for UMLExamples test suite'

	def tasks = [
		generateUMLTestSuite,
		compileUMLTestSuite
	]
	
	for (int i = 0; i < tasks.size() - 1; i++) {
        tasks[i + 1].mustRunAfter(tasks[i])
    }
    
    dependsOn(tasks)
}