#ifndef NEWMODEL_PRIMECHECKER__HPP
#define NEWMODEL_PRIMECHECKER__HPP

//********************************************************************
//*    
//* Warning: This file was generated by Mesapp Generator
//*
//********************************************************************


#include <QtCore/QObject>
#include <QtCore/QList>
#include <QtCore/QVariant>
#include <boost/any.hpp>


//*********************************
// generated Includes
 

//Forward Declaration for used types





// base class includes

#include "Element.hpp"

// enum includes


//*********************************

namespace NewModel {

class PrimeChecker : virtual public uml::Element
{


private:    
Q_DISABLE_COPY( PrimeChecker) 

protected:
	PrimeChecker(){}

public:

//destructor
virtual ~PrimeChecker() {}


//*********************************
// Getter Setter
//*********************************
virtual int getNumber() const = 0;
virtual void setNumber (int _number)= 0; 
virtual int getDivider() const = 0;
virtual void setDivider (int _divider)= 0; 


//*********************************
// Operations
//*********************************
virtual bool divides(  ) = 0;
virtual void next(  ) = 0;
virtual void printIsPrime(  ) = 0;
virtual void printNotPrime(  ) = 0;
virtual bool isOdd(  ) = 0;
virtual bool isNotFinished(  ) = 0;




protected:

//*********************************
// Members
//*********************************
int m_number =  9949 /*defined default value*/ ;
int m_divider =  3 /*defined default value*/ ;




private:

};

}

#endif /* end of include guard: NEWMODEL_PRIMECHECKER__HPP */

