<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage
    xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="libraryModel_ecore"
    nsURI="http://www.example.org/libraryModel_ecore"
    nsPrefix="libraryModel_ecore">
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Book"
      eSuperTypes="#//NamedElement">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="authors"
        upperBound="-1"
        eType="#//Author"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="library"
        eType="#//LibraryModel"
        eOpposite="#//LibraryModel/book"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="pictures"
        upperBound="-1"
        eType="#//Picture"
        containment="true"
        eOpposite="#//Picture/book"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Author"
      eSuperTypes="#//NamedElement"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="LibraryModel">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="book"
        upperBound="-1"
        eType="#//Book"
        containment="true"
        eOpposite="#//Book/library"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="authors"
        upperBound="-1"
        eType="#//Author"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="NamedElement">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="Name"
        eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//String"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Picture"
      eSuperTypes="#//NamedElement">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="book"
        eType="#//Book"
        eOpposite="#//Book/pictures"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="pageNumber"
        eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
  </eClassifiers>
</ecore:EPackage>
