/*
 * MDE4CPP - Model Driven Engineering for C++
 *
 * Copyright (c) TU Ilmenau, Systems and Software Engineering Group
 * All rights reserved.
 *
 * MIT License
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this
 * software and associated documentation files (the "Software"), to deal in the Software
 * without restriction, including without limitation the rights to use, copy, modify, merge,
 * publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons
 * to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or
 * substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED *AS IS*, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
 * PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
 * FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */
plugins{
	id "tui.sse.mde4cpp.MDE4CPPGenerate" version "0.6"	
}

description 'Example collection'

import org.gradle.internal.os.OperatingSystem;

// Wrapper task for all included build subprojects
task generateAllExamples() {
	group 'Examples'
	description 'Generate all model examples from included builds'

	dependsOn gradle.includedBuild('ecoreExamples').task(':generateEcoreModelExamples')
	dependsOn gradle.includedBuild('UMLExamples').task(':generateUMLModelExamples')
	dependsOn gradle.includedBuild('fUMLExamples').task(':generatefUMLModelExamples')
	dependsOn gradle.includedBuild('PSCSExamples').task(':generatePSCSModelExamples')
	dependsOn gradle.includedBuild('PSSMExamples').task(':generatePSSMModelExamples')
	dependsOn gradle.includedBuild('oclExamples').task(':generateOCLModelExamples')
	dependsOn gradle.includedBuild('strategiesExamples').task(':generateStrategiesExamplesModelExamples')
}

task compileAllExamples() {
	group 'Examples'
	description 'compile applications for all examples from included builds'

	dependsOn gradle.includedBuild('commonExamples').task(':compileCommonExamples')
	dependsOn gradle.includedBuild('ecoreExamples').task(':compileEcoreExamples')
	dependsOn gradle.includedBuild('ecoreExamples').task(':compileEcoreModelExamples')
	dependsOn gradle.includedBuild('UMLExamples').task(':compileUMLExamples')
	dependsOn gradle.includedBuild('UMLExamples').task(':compileUMLModelExamples')
	dependsOn gradle.includedBuild('fUMLExamples').task(':compilefUMLModelExamples')
	dependsOn gradle.includedBuild('PSCSExamples').task(':compilePSCSModelExamples')
	dependsOn gradle.includedBuild('PSSMExamples').task(':compilePSSMModelExamples')
	dependsOn gradle.includedBuild('oclExamples').task(':compileOCLExamples')
	dependsOn gradle.includedBuild('oclExamples').task(':compileOCLModelExamples')
	dependsOn gradle.includedBuild('strategiesExamples').task(':compileStrategiesExamplesModelExamples')
}																

task buildAllExamples(){
	group 'Examples'
	description 'generate and compile all example applications'
	
	def tasks = [
		generateAllExamples,
		compileAllExamples
	]
	
	for (int i = 0; i < tasks.size() - 1; i++) {
        tasks[i + 1].mustRunAfter(tasks[i])
    }
    
    dependsOn(tasks)
}

task cleanAllExamples(type: Exec){
	group 'Examples'
	description 'Removes all generated files in examples directory'
	
    workingDir System.env.MDE4CPP_HOME
    
    if(OperatingSystem.current().isWindows()){
    	commandLine 'cmd', '/c', 'git clean -d -f -X', 'src\\examples'
	} else if(OperatingSystem.current().isLinux() || OperatingSystem.current().isMacOsX()){
		commandLine '/bin/sh', '-c', 'git clean -d -f -X src/examples'
	}
}

task generateAllTests() {
	group 'Tests'
	description 'generate all test suites from included builds'

	dependsOn gradle.includedBuild('ecoreExamples').task(':generateEcoreTestSuite')
	dependsOn gradle.includedBuild('UMLExamples').task(':generateUMLTestSuite')
	dependsOn gradle.includedBuild('fUMLExamples').task(':generatefUMLTestSuite')
	dependsOn gradle.includedBuild('PSCSExamples').task(':generatePSCSTestSuite')
	dependsOn gradle.includedBuild('PSSMExamples').task(':generatePSSMTestSuite')
	dependsOn gradle.includedBuild('oclExamples').task(':generateOCLTestSuite')
	dependsOn gradle.includedBuild('strategiesExamples').task(':generateStrategiesExamplesTestSuite')
}

task compileAllTests() {
	group 'Tests'
	description 'compile all test suites from included builds'

	dependsOn gradle.includedBuild('ecoreExamples').task(':compileEcoreTestSuite')
	dependsOn gradle.includedBuild('UMLExamples').task(':compileUMLTestSuite')
	dependsOn gradle.includedBuild('fUMLExamples').task(':compilefUMLTestSuite')
	dependsOn gradle.includedBuild('PSCSExamples').task(':compilePSCSTestSuite')
	dependsOn gradle.includedBuild('PSSMExamples').task(':compilePSSMTestSuite')
	dependsOn gradle.includedBuild('oclExamples').task(':compileOCLTestSuite')
	dependsOn gradle.includedBuild('strategiesExamples').task(':compileStrategiesExamplesTestSuite')
}

task buildAllTests() {
	group 'Tests'
	description 'generate and compile applications for all test suites from included builds'

	dependsOn gradle.includedBuild('ecoreExamples').task(':buildEcoreTestSuite')
	dependsOn gradle.includedBuild('UMLExamples').task(':buildUMLTestSuite')
	dependsOn gradle.includedBuild('fUMLExamples').task(':buildfUMLTestSuite')
	dependsOn gradle.includedBuild('PSCSExamples').task(':buildPSCSTestSuite')
	dependsOn gradle.includedBuild('PSSMExamples').task(':buildPSSMTestSuite')
	dependsOn gradle.includedBuild('oclExamples').task(':buildOCLTestSuite')
	dependsOn gradle.includedBuild('strategiesExamples').task(':buildStrategiesExamplesTestSuite')
}