services:
  # =============================================
  # Application Models: FoundationalModelLibrary
  # =============================================
  build-foundational-model-library:
    profiles: ["application"]
    extends:
      file: base.yml
      service: base-service
    container_name: mde4cpp-build-foundational-model-library
    command: >-
      /bin/bash -c "
      ./application/tools/gradlew src:common:FoundationalModelLibrary:generateFoundationalModelLibrary --no-daemon &&
      ./application/tools/gradlew src:common:FoundationalModelLibrary:compileFoundationalModelLibrary --no-daemon
      "
  generate-foundational-model-library:
    profiles: ["application"]
    extends:
      file: base.yml
      service: base-service
    container_name: mde4cpp-generate-foundational-model-library
    command: ./application/tools/gradlew src:common:FoundationalModelLibrary:generateFoundationalModelLibrary --no-daemon
  compile-foundational-model-library:
    profiles: ["application"]
    extends:
      file: base.yml
      service: base-service
    container_name: mde4cpp-compile-foundational-model-library
