services:
  base-service:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        USER_UID: ${UID:-1000}
        USER_GID: ${GID:-1000}
    image: mde4cpp:latest
    init: true
    user: mde4cpp
    working_dir: /home/mde4cpp
    volumes:
      - ../:/home/mde4cpp
      - gradle_cache:/home/mde4cpp/.gradle
      - eclipse_data:/home/eclipse
    entrypoint: ["/bin/bash", "/home/mde4cpp/docker/scripts/entrypoint.sh"]
