services:
  # ==================
  # Core Models: Ecore
  # ==================
  build-ecore:
    profiles: ["core"]
    extends:
      file: base.yml
      service: base-service
    container_name: mde4cpp-build-ecore
    command: >-
      /bin/bash -c "
      ./application/tools/gradlew src:ecore:generateEcore --no-daemon &&
      ./application/tools/gradlew src:ecore:compileEcore --no-daemon
      "
  generate-ecore:
    profiles: ["core"]
    extends:
      file: base.yml
      service: base-service
    container_name: mde4cpp-generate-ecore
    command: ./application/tools/gradlew src:ecore:generateEcore --no-daemon
  compile-ecore:
    profiles: ["core"]
    extends:
      file: base.yml
      service: base-service
    container_name: mde4cpp-compile-ecore
    command: ./application/tools/gradlew src:ecore:compileEcore --no-daemon
  # ==================
  # Core Models: Types
  # ==================
  build-types:
    profiles: ["core"]
    extends:
      file: base.yml
      service: base-service
    container_name: mde4cpp-build-types
    command: >-
      /bin/bash -c "
      ./application/tools/gradlew src:uml:types:generateTypes --no-daemon &&
      ./application/tools/gradlew src:uml:types:compileTypes --no-daemon
      "
  generate-types:
    profiles: ["core"]
    extends:
      file: base.yml
      service: base-service
    container_name: mde4cpp-generate-types
    command: ./application/tools/gradlew src:uml:types:generateTypes --no-daemon
  compile-types:
    profiles: ["core"]
    extends:
      file: base.yml
      service: base-service
    container_name: mde4cpp-compile-types
    command: ./application/tools/gradlew src:uml:types:compileTypes --no-daemon
  # ================
  # Core Models: UML
  # ================
  build-uml:
    profiles: ["core"]
    extends:
      file: base.yml
      service: base-service
    container_name: mde4cpp-build-uml
    command: >-
      /bin/bash -c "
      ./application/tools/gradlew src:uml:uml:generateUml --no-daemon &&
      ./application/tools/gradlew src:uml:uml:compileUml --no-daemon
      "
  generate-uml:
    profiles: ["core"]
    extends:
      file: base.yml
      service: base-service
    container_name: mde4cpp-generate-uml
    command: ./application/tools/gradlew src:uml:uml:generateUml --no-daemon
  compile-uml:
    profiles: ["core"]
    extends:
      file: base.yml
      service: base-service
    container_name: mde4cpp-compile-uml
    command: ./application/tools/gradlew src:uml:uml:compileUml --no-daemon
