services:
  # ==========
  # OCL Models
  # ==========
  build-ocl-model:
    profiles: ["ocl"]
    extends:
      file: base.yml
      service: base-service
    container_name: mde4cpp-build-ocl-model
    command: >-
      /bin/bash -c "
      ./application/tools/gradlew src:ocl:oclModel:generateOcl --no-daemon &&
      ./application/tools/gradlew src:ocl:oclModel:compileOcl --no-daemon
      "
  generate-ocl:
    profiles: ["ocl"]
    extends:
      file: base.yml
      service: base-service
    container_name: mde4cpp-generate-ocl
    command: ./application/tools/gradlew src:ocl:oclModel:generateOcl --no-daemon
  compile-ocl:
    profiles: ["ocl"]
    extends:
      file: base.yml
      service: base-service
    container_name: mde4cpp-compile-ocl
    command: ./application/tools/gradlew src:ocl:oclModel:compileOcl --no-daemon
  build-ocl-parser:
    profiles: ["ocl"]
    extends:
      file: base.yml
      service: base-service
    container_name: mde4cpp-build-ocl-parser
    command: >-
      /bin/bash -c "
      ./application/tools/gradlew src:ocl:oclParser:generateOclParser --no-daemon &&
      ./application/tools/gradlew src:ocl:oclParser:compileOclParser --no-daemon
      "
  generate-ocl-parser:
    profiles: ["ocl"]
    extends:
      file: base.yml
      service: base-service
    container_name: mde4cpp-generate-ocl-parser
    command: ./application/tools/gradlew src:ocl:oclParser:generateOclParser --no-daemon
  compile-ocl-parser:
    profiles: ["ocl"]
    extends:
      file: base.yml
      service: base-service
    container_name: mde4cpp-compile-ocl-parser
    command: ./application/tools/gradlew src:ocl:oclParser:compileOclParser --no-daemon
