services:
  # ===============================
  # Profile Models: StandardProfile
  # ===============================
  build-standard-profile:
    profiles: ["uml-profiles"]
    extends:
      file: base.yml
      service: base-service
    container_name: mde4cpp-build-standard-profile
    command: >-
      /bin/bash -c "
      ./application/tools/gradlew src:common:standardProfile:generateStandardProfile --no-daemon &&
      ./application/tools/gradlew src:common:standardProfile:compileStandardProfile --no-daemon
      "
  generate-standard-profile:
    profiles: ["uml-profiles"]
    extends:
      file: base.yml
      service: base-service
    container_name: mde4cpp-generate-standard-profile
    command: ./application/tools/gradlew src:common:standardProfile:generateStandardProfile --no-daemon
  compile-standard-profile:
    profiles: ["uml-profiles"]
    extends:
      file: base.yml
      service: base-service
    container_name: mde4cpp-compile-standard-profile
    command: ./application/tools/gradlew src:common:standardProfile:compileStandardProfile --no-daemon
  # ==============================
  # Profile Models: UML4CPPProfile
  # ==============================
  build-uml4cpp-profile:
    profiles: ["uml-profiles"]
    extends:
      file: base.yml
      service: base-service
    container_name: mde4cpp-build-uml4cpp-profile
    command: >-
      /bin/bash -c "
      ./application/tools/gradlew src:common:UML4CPPProfile:generateUML4CPPProfile --no-daemon &&
      ./application/tools/gradlew src:common:UML4CPPProfile:compileUML4CPPProfile --no-daemon
      "
  generate-uml4cpp-profile:
    profiles: ["uml-profiles"]
    extends:
      file: base.yml
      service: base-service
    container_name: mde4cpp-generate-uml4cpp-profile
    command: ./application/tools/gradlew src:common:UML4CPPProfile:generateUML4CPPProfile --no-daemon
  compile-uml4cpp-profile:
    profiles: ["uml-profiles"]
    extends:
      file: base.yml
      service: base-service
    container_name: mde4cpp-compile-uml4cpp-profile
    command: ./application/tools/gradlew src:common:UML4CPPProfile:compileUML4CPPProfile --no-daemon
