#include "forkNodeTest/impl/ForkNodeTestPackageImpl.hpp"

//meta meta model classes
#include "uml/Activity.hpp"
#include "uml/ActivityFinalNode.hpp"
#include "uml/CallBehaviorAction.hpp"
#include "uml/Class.hpp"
#include "uml/ControlFlow.hpp"
#include "uml/ForkNode.hpp"
#include "uml/FunctionBehavior.hpp"
#include "uml/InitialNode.hpp"
#include "uml/LiteralBoolean.hpp"
#include "uml/LiteralInteger.hpp"

#include "abstractDataTypes/SubsetUnion.hpp"
#include "uml/VisibilityKind.hpp"
//meta meta model factory
#include "uml/UmlFactory.hpp"

//metamodel factory
#include "forkNodeTest/ForkNodeTestFactory.hpp"

//depending model packages



using namespace forkNodeTest;

ForkNodeTestPackageImpl::ForkNodeTestPackageImpl()
{
}

ForkNodeTestPackageImpl::~ForkNodeTestPackageImpl()
{
}

bool ForkNodeTestPackageImpl::isInited = false;

ForkNodeTestPackage* ForkNodeTestPackageImpl::create()
{
	if (isInited)
	{
		return ForkNodeTestPackage::eInstance().get();
	}
	isInited = true;
	
    // Obtain or create and register package, create package meta-data objects
    ForkNodeTestPackageImpl * metaModelPackage = new ForkNodeTestPackageImpl();
    return metaModelPackage;
}

void ForkNodeTestPackageImpl::init(std::shared_ptr<uml::Package> forkNodeTest)
{
    // Initialize created meta-data
	setThisPackagePtr(forkNodeTest);
	initMetaModel();
    createPackageContents(forkNodeTest);
    initializePackageContents(forkNodeTest);   
}

void ForkNodeTestPackageImpl::initMetaModel()
{
}

void ForkNodeTestPackageImpl::createPackageContents(std::shared_ptr<uml::Package> forkNodeTest)
{
	if (isCreated)
	{
		return;
	}
	isCreated = true;

	std::shared_ptr<uml::UmlFactory> factory = uml::UmlFactory::eInstance();

	createPackageValueSpecifications(forkNodeTest, factory);
	createPackageInterfaces(forkNodeTest, factory);
	createPackageClasses(forkNodeTest, factory);
	createPackageInstanceSpecifications(forkNodeTest, factory);
	createPackageStereotypes(forkNodeTest, factory);
	createPackageActivities(forkNodeTest, factory);
	createPackageDependencies(forkNodeTest, factory);
	createPackagePrimitiveTypes(forkNodeTest, factory);
	createPackageEnumerationLiterals(forkNodeTest, factory);
	createPackageInterfaceRealizations(forkNodeTest, factory);
}

void ForkNodeTestPackageImpl::createPackageActivities(std::shared_ptr<uml::Package> forkNodeTest, std::shared_ptr<uml::UmlFactory> factory)
{
	forkNodeTest_forkClass_forkNodeTest = factory->createActivity_in_Package(forkNodeTest);
	
	
	//Node
	forkNodeTest_forkClass_forkNodeTestActivityFinal1 = factory->createActivityFinalNode_in_Activity(forkNodeTest_forkClass_forkNodeTest);
	forkNodeTest_forkClass_forkNodeTestActivityFinal1->setName("ActivityFinal1");
	forkNodeTest_forkClass_forkNodeTestActivityFinal2 = factory->createActivityFinalNode_in_Activity(forkNodeTest_forkClass_forkNodeTest);
	forkNodeTest_forkClass_forkNodeTestActivityFinal2->setName("ActivityFinal2");
	forkNodeTest_forkClass_forkNodeTestFork1 = factory->createForkNode_in_Activity(forkNodeTest_forkClass_forkNodeTest);
	forkNodeTest_forkClass_forkNodeTestFork1->setName("Fork1");
	forkNodeTest_forkClass_forkNodeTestInitial1 = factory->createInitialNode_in_Activity(forkNodeTest_forkClass_forkNodeTest);
	forkNodeTest_forkClass_forkNodeTestInitial1->setName("Initial1");
	forkNodeTest_forkClass_forkNodeTestcbaA = factory->createCallBehaviorAction_in_Activity(forkNodeTest_forkClass_forkNodeTest);
	forkNodeTest_forkClass_forkNodeTestcbaA->setName("cbaA");
	//CallBehaviorAction cbaA
	forkNodeTest_forkClass_forkNodeTestcbaA->setBehavior(forkNodeTest_forkClass_fbNull);
	forkNodeTest_forkClass_forkNodeTestcbaA->setIsSynchronous(true); //imposed by the fUML specification
	
	forkNodeTest_forkClass_forkNodeTestcbaB = factory->createCallBehaviorAction_in_Activity(forkNodeTest_forkClass_forkNodeTest);
	forkNodeTest_forkClass_forkNodeTestcbaB->setName("cbaB");
	//CallBehaviorAction cbaB
	forkNodeTest_forkClass_forkNodeTestcbaB->setBehavior(forkNodeTest_forkClass_fbNull);
	forkNodeTest_forkClass_forkNodeTestcbaB->setIsSynchronous(true); //imposed by the fUML specification
	
	forkNodeTest_forkClass_forkNodeTestcbaC = factory->createCallBehaviorAction_in_Activity(forkNodeTest_forkClass_forkNodeTest);
	forkNodeTest_forkClass_forkNodeTestcbaC->setName("cbaC");
	//CallBehaviorAction cbaC
	forkNodeTest_forkClass_forkNodeTestcbaC->setBehavior(forkNodeTest_forkClass_fbNull);
	forkNodeTest_forkClass_forkNodeTestcbaC->setIsSynchronous(true); //imposed by the fUML specification
	
	forkNodeTest_forkClass_forkNodeTestcbaD = factory->createCallBehaviorAction_in_Activity(forkNodeTest_forkClass_forkNodeTest);
	forkNodeTest_forkClass_forkNodeTestcbaD->setName("cbaD");
	//CallBehaviorAction cbaD
	forkNodeTest_forkClass_forkNodeTestcbaD->setBehavior(forkNodeTest_forkClass_fbNull);
	forkNodeTest_forkClass_forkNodeTestcbaD->setIsSynchronous(true); //imposed by the fUML specification
	
	forkNodeTest_forkClass_forkNodeTestcbaE = factory->createCallBehaviorAction_in_Activity(forkNodeTest_forkClass_forkNodeTest);
	forkNodeTest_forkClass_forkNodeTestcbaE->setName("cbaE");
	//CallBehaviorAction cbaE
	forkNodeTest_forkClass_forkNodeTestcbaE->setBehavior(forkNodeTest_forkClass_fbNull);
	forkNodeTest_forkClass_forkNodeTestcbaE->setIsSynchronous(true); //imposed by the fUML specification
	
	forkNodeTest_forkClass_forkNodeTestcbaF = factory->createCallBehaviorAction_in_Activity(forkNodeTest_forkClass_forkNodeTest);
	forkNodeTest_forkClass_forkNodeTestcbaF->setName("cbaF");
	//CallBehaviorAction cbaF
	forkNodeTest_forkClass_forkNodeTestcbaF->setBehavior(forkNodeTest_forkClass_fbNull);
	forkNodeTest_forkClass_forkNodeTestcbaF->setIsSynchronous(true); //imposed by the fUML specification
	
	forkNodeTest_forkClass_forkNodeTestcbaG = factory->createCallBehaviorAction_in_Activity(forkNodeTest_forkClass_forkNodeTest);
	forkNodeTest_forkClass_forkNodeTestcbaG->setName("cbaG");
	//CallBehaviorAction cbaG
	forkNodeTest_forkClass_forkNodeTestcbaG->setBehavior(forkNodeTest_forkClass_fbNull);
	forkNodeTest_forkClass_forkNodeTestcbaG->setIsSynchronous(true); //imposed by the fUML specification
	
	forkNodeTest_forkClass_forkNodeTestcbaH = factory->createCallBehaviorAction_in_Activity(forkNodeTest_forkClass_forkNodeTest);
	forkNodeTest_forkClass_forkNodeTestcbaH->setName("cbaH");
	//CallBehaviorAction cbaH
	forkNodeTest_forkClass_forkNodeTestcbaH->setBehavior(forkNodeTest_forkClass_fbNull);
	forkNodeTest_forkClass_forkNodeTestcbaH->setIsSynchronous(true); //imposed by the fUML specification
	
	forkNodeTest_forkClass_forkNodeTestcbaI = factory->createCallBehaviorAction_in_Activity(forkNodeTest_forkClass_forkNodeTest);
	forkNodeTest_forkClass_forkNodeTestcbaI->setName("cbaI");
	//CallBehaviorAction cbaI
	forkNodeTest_forkClass_forkNodeTestcbaI->setBehavior(forkNodeTest_forkClass_fbNull);
	forkNodeTest_forkClass_forkNodeTestcbaI->setIsSynchronous(true); //imposed by the fUML specification
	
	forkNodeTest_forkClass_forkNodeTestcbaJ = factory->createCallBehaviorAction_in_Activity(forkNodeTest_forkClass_forkNodeTest);
	forkNodeTest_forkClass_forkNodeTestcbaJ->setName("cbaJ");
	//CallBehaviorAction cbaJ
	forkNodeTest_forkClass_forkNodeTestcbaJ->setBehavior(forkNodeTest_forkClass_fbNull);
	forkNodeTest_forkClass_forkNodeTestcbaJ->setIsSynchronous(true); //imposed by the fUML specification
	
	forkNodeTest_forkClass_forkNodeTestcbaK = factory->createCallBehaviorAction_in_Activity(forkNodeTest_forkClass_forkNodeTest);
	forkNodeTest_forkClass_forkNodeTestcbaK->setName("cbaK");
	//CallBehaviorAction cbaK
	forkNodeTest_forkClass_forkNodeTestcbaK->setBehavior(forkNodeTest_forkClass_fbNull);
	forkNodeTest_forkClass_forkNodeTestcbaK->setIsSynchronous(true); //imposed by the fUML specification
	
	forkNodeTest_forkClass_forkNodeTestcbaL = factory->createCallBehaviorAction_in_Activity(forkNodeTest_forkClass_forkNodeTest);
	forkNodeTest_forkClass_forkNodeTestcbaL->setName("cbaL");
	//CallBehaviorAction cbaL
	forkNodeTest_forkClass_forkNodeTestcbaL->setBehavior(forkNodeTest_forkClass_fbNull);
	forkNodeTest_forkClass_forkNodeTestcbaL->setIsSynchronous(true); //imposed by the fUML specification
	
	
	//flow
	cF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaA = factory->createControlFlow_in_Activity(forkNodeTest_forkClass_forkNodeTest);
	cF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaA->setName("");
	cF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaE = factory->createControlFlow_in_Activity(forkNodeTest_forkClass_forkNodeTest);
	cF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaE->setName("");
	cF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaI = factory->createControlFlow_in_Activity(forkNodeTest_forkClass_forkNodeTest);
	cF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaI->setName("");
	cF_forkNodeTest_forkClass_forkNodeTestInitial1_forkNodeTest_forkClass_forkNodeTestFork1 = factory->createControlFlow_in_Activity(forkNodeTest_forkClass_forkNodeTest);
	cF_forkNodeTest_forkClass_forkNodeTestInitial1_forkNodeTest_forkClass_forkNodeTestFork1->setName("");
	cF_forkNodeTest_forkClass_forkNodeTestcbaA_forkNodeTest_forkClass_forkNodeTestcbaB = factory->createControlFlow_in_Activity(forkNodeTest_forkClass_forkNodeTest);
	cF_forkNodeTest_forkClass_forkNodeTestcbaA_forkNodeTest_forkClass_forkNodeTestcbaB->setName("");
	cF_forkNodeTest_forkClass_forkNodeTestcbaB_forkNodeTest_forkClass_forkNodeTestcbaC = factory->createControlFlow_in_Activity(forkNodeTest_forkClass_forkNodeTest);
	cF_forkNodeTest_forkClass_forkNodeTestcbaB_forkNodeTest_forkClass_forkNodeTestcbaC->setName("");
	cF_forkNodeTest_forkClass_forkNodeTestcbaC_forkNodeTest_forkClass_forkNodeTestcbaD = factory->createControlFlow_in_Activity(forkNodeTest_forkClass_forkNodeTest);
	cF_forkNodeTest_forkClass_forkNodeTestcbaC_forkNodeTest_forkClass_forkNodeTestcbaD->setName("");
	cF_forkNodeTest_forkClass_forkNodeTestcbaD_forkNodeTest_forkClass_forkNodeTestActivityFinal2 = factory->createControlFlow_in_Activity(forkNodeTest_forkClass_forkNodeTest);
	cF_forkNodeTest_forkClass_forkNodeTestcbaD_forkNodeTest_forkClass_forkNodeTestActivityFinal2->setName("");
	cF_forkNodeTest_forkClass_forkNodeTestcbaE_forkNodeTest_forkClass_forkNodeTestcbaF = factory->createControlFlow_in_Activity(forkNodeTest_forkClass_forkNodeTest);
	cF_forkNodeTest_forkClass_forkNodeTestcbaE_forkNodeTest_forkClass_forkNodeTestcbaF->setName("");
	cF_forkNodeTest_forkClass_forkNodeTestcbaF_forkNodeTest_forkClass_forkNodeTestcbaG = factory->createControlFlow_in_Activity(forkNodeTest_forkClass_forkNodeTest);
	cF_forkNodeTest_forkClass_forkNodeTestcbaF_forkNodeTest_forkClass_forkNodeTestcbaG->setName("");
	cF_forkNodeTest_forkClass_forkNodeTestcbaG_forkNodeTest_forkClass_forkNodeTestcbaH = factory->createControlFlow_in_Activity(forkNodeTest_forkClass_forkNodeTest);
	cF_forkNodeTest_forkClass_forkNodeTestcbaG_forkNodeTest_forkClass_forkNodeTestcbaH->setName("");
	cF_forkNodeTest_forkClass_forkNodeTestcbaH_forkNodeTest_forkClass_forkNodeTestcbaL = factory->createControlFlow_in_Activity(forkNodeTest_forkClass_forkNodeTest);
	cF_forkNodeTest_forkClass_forkNodeTestcbaH_forkNodeTest_forkClass_forkNodeTestcbaL->setName("");
	cF_forkNodeTest_forkClass_forkNodeTestcbaI_forkNodeTest_forkClass_forkNodeTestcbaJ = factory->createControlFlow_in_Activity(forkNodeTest_forkClass_forkNodeTest);
	cF_forkNodeTest_forkClass_forkNodeTestcbaI_forkNodeTest_forkClass_forkNodeTestcbaJ->setName("");
	cF_forkNodeTest_forkClass_forkNodeTestcbaJ_forkNodeTest_forkClass_forkNodeTestcbaF = factory->createControlFlow_in_Activity(forkNodeTest_forkClass_forkNodeTest);
	cF_forkNodeTest_forkClass_forkNodeTestcbaJ_forkNodeTest_forkClass_forkNodeTestcbaF->setName("");
	cF_forkNodeTest_forkClass_forkNodeTestcbaJ_forkNodeTest_forkClass_forkNodeTestcbaK = factory->createControlFlow_in_Activity(forkNodeTest_forkClass_forkNodeTest);
	cF_forkNodeTest_forkClass_forkNodeTestcbaJ_forkNodeTest_forkClass_forkNodeTestcbaK->setName("");
	cF_forkNodeTest_forkClass_forkNodeTestcbaK_forkNodeTest_forkClass_forkNodeTestcbaL = factory->createControlFlow_in_Activity(forkNodeTest_forkClass_forkNodeTest);
	cF_forkNodeTest_forkClass_forkNodeTestcbaK_forkNodeTest_forkClass_forkNodeTestcbaL->setName("");
	cF_forkNodeTest_forkClass_forkNodeTestcbaL_forkNodeTest_forkClass_forkNodeTestActivityFinal1 = factory->createControlFlow_in_Activity(forkNodeTest_forkClass_forkNodeTest);
	cF_forkNodeTest_forkClass_forkNodeTestcbaL_forkNodeTest_forkClass_forkNodeTestActivityFinal1->setName("");
	
}

void ForkNodeTestPackageImpl::createPackageClasses(std::shared_ptr<uml::Package> forkNodeTest, std::shared_ptr<uml::UmlFactory> factory)
{
	std::shared_ptr<uml::Constraint> con = nullptr;
	std::shared_ptr<uml::OpaqueExpression> oe = nullptr;

	// forkClass
	forkNodeTest_forkClass = factory->createClass_in_Package(forkNodeTest);
	
    // forkClass function behaviors
	forkNodeTest_forkClass_fbNull = factory->createFunctionBehavior_in_BehavioredClassifier(forkNodeTest_forkClass);
	

}

void ForkNodeTestPackageImpl::createPackageDependencies(std::shared_ptr<uml::Package> forkNodeTest, std::shared_ptr<uml::UmlFactory> factory)
{
}

void ForkNodeTestPackageImpl::createPackageEnumerationLiterals(std::shared_ptr<uml::Package> forkNodeTest, std::shared_ptr<uml::UmlFactory> factory)
{
}

void ForkNodeTestPackageImpl::createPackageInstanceSpecifications(std::shared_ptr<uml::Package> forkNodeTest, std::shared_ptr<uml::UmlFactory> factory)
{
}

void ForkNodeTestPackageImpl::createPackageInterfaceRealizations(std::shared_ptr<uml::Package> forkNodeTest, std::shared_ptr<uml::UmlFactory> factory)
{
}

void ForkNodeTestPackageImpl::createPackageInterfaces(std::shared_ptr<uml::Package> forkNodeTest, std::shared_ptr<uml::UmlFactory> factory)
{
}

void ForkNodeTestPackageImpl::createPackagePrimitiveTypes(std::shared_ptr<uml::Package> forkNodeTest, std::shared_ptr<uml::UmlFactory> factory)
{
}

void ForkNodeTestPackageImpl::createPackageStereotypes(std::shared_ptr<uml::Package> forkNodeTest, std::shared_ptr<uml::UmlFactory> factory)
{
}

void ForkNodeTestPackageImpl::createPackageValueSpecifications(std::shared_ptr<uml::Package> forkNodeTest, std::shared_ptr<uml::UmlFactory> factory)
{
	cF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaA_guard_LiteralBoolean_CF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaA = factory->createLiteralBoolean_in_Namespace(std::dynamic_pointer_cast<uml::Namespace>(cF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaA));
	cF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaA_guard_LiteralBoolean_CF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaA->setValue(true);

	cF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaA_weight_LiteralInteger_CF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaA = factory->createLiteralInteger_in_Namespace(std::dynamic_pointer_cast<uml::Namespace>(cF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaA));
	cF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaA_weight_LiteralInteger_CF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaA->setValue(0);

	cF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaE_guard_LiteralBoolean_CF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaE = factory->createLiteralBoolean_in_Namespace(std::dynamic_pointer_cast<uml::Namespace>(cF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaE));
	cF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaE_guard_LiteralBoolean_CF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaE->setValue(true);

	cF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaE_weight_LiteralInteger_CF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaE = factory->createLiteralInteger_in_Namespace(std::dynamic_pointer_cast<uml::Namespace>(cF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaE));
	cF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaE_weight_LiteralInteger_CF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaE->setValue(0);

	cF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaI_guard_LiteralBoolean_CF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaI = factory->createLiteralBoolean_in_Namespace(std::dynamic_pointer_cast<uml::Namespace>(cF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaI));
	cF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaI_guard_LiteralBoolean_CF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaI->setValue(true);

	cF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaI_weight_LiteralInteger_CF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaI = factory->createLiteralInteger_in_Namespace(std::dynamic_pointer_cast<uml::Namespace>(cF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaI));
	cF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaI_weight_LiteralInteger_CF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaI->setValue(0);

	cF_forkNodeTest_forkClass_forkNodeTestInitial1_forkNodeTest_forkClass_forkNodeTestFork1_guard_LiteralBoolean_CF_forkNodeTest_forkClass_forkNodeTestInitial1_forkNodeTest_forkClass_forkNodeTestFork1 = factory->createLiteralBoolean_in_Namespace(std::dynamic_pointer_cast<uml::Namespace>(cF_forkNodeTest_forkClass_forkNodeTestInitial1_forkNodeTest_forkClass_forkNodeTestFork1));
	cF_forkNodeTest_forkClass_forkNodeTestInitial1_forkNodeTest_forkClass_forkNodeTestFork1_guard_LiteralBoolean_CF_forkNodeTest_forkClass_forkNodeTestInitial1_forkNodeTest_forkClass_forkNodeTestFork1->setValue(true);

	cF_forkNodeTest_forkClass_forkNodeTestInitial1_forkNodeTest_forkClass_forkNodeTestFork1_weight_LiteralInteger_CF_forkNodeTest_forkClass_forkNodeTestInitial1_forkNodeTest_forkClass_forkNodeTestFork1 = factory->createLiteralInteger_in_Namespace(std::dynamic_pointer_cast<uml::Namespace>(cF_forkNodeTest_forkClass_forkNodeTestInitial1_forkNodeTest_forkClass_forkNodeTestFork1));
	cF_forkNodeTest_forkClass_forkNodeTestInitial1_forkNodeTest_forkClass_forkNodeTestFork1_weight_LiteralInteger_CF_forkNodeTest_forkClass_forkNodeTestInitial1_forkNodeTest_forkClass_forkNodeTestFork1->setValue(0);

	cF_forkNodeTest_forkClass_forkNodeTestcbaA_forkNodeTest_forkClass_forkNodeTestcbaB_guard_LiteralBoolean_CF_forkNodeTest_forkClass_forkNodeTestcbaA_forkNodeTest_forkClass_forkNodeTestcbaB = factory->createLiteralBoolean_in_Namespace(std::dynamic_pointer_cast<uml::Namespace>(cF_forkNodeTest_forkClass_forkNodeTestcbaA_forkNodeTest_forkClass_forkNodeTestcbaB));
	cF_forkNodeTest_forkClass_forkNodeTestcbaA_forkNodeTest_forkClass_forkNodeTestcbaB_guard_LiteralBoolean_CF_forkNodeTest_forkClass_forkNodeTestcbaA_forkNodeTest_forkClass_forkNodeTestcbaB->setValue(true);

	cF_forkNodeTest_forkClass_forkNodeTestcbaA_forkNodeTest_forkClass_forkNodeTestcbaB_weight_LiteralInteger_CF_forkNodeTest_forkClass_forkNodeTestcbaA_forkNodeTest_forkClass_forkNodeTestcbaB = factory->createLiteralInteger_in_Namespace(std::dynamic_pointer_cast<uml::Namespace>(cF_forkNodeTest_forkClass_forkNodeTestcbaA_forkNodeTest_forkClass_forkNodeTestcbaB));
	cF_forkNodeTest_forkClass_forkNodeTestcbaA_forkNodeTest_forkClass_forkNodeTestcbaB_weight_LiteralInteger_CF_forkNodeTest_forkClass_forkNodeTestcbaA_forkNodeTest_forkClass_forkNodeTestcbaB->setValue(0);

	cF_forkNodeTest_forkClass_forkNodeTestcbaB_forkNodeTest_forkClass_forkNodeTestcbaC_guard_LiteralBoolean_CF_forkNodeTest_forkClass_forkNodeTestcbaB_forkNodeTest_forkClass_forkNodeTestcbaC = factory->createLiteralBoolean_in_Namespace(std::dynamic_pointer_cast<uml::Namespace>(cF_forkNodeTest_forkClass_forkNodeTestcbaB_forkNodeTest_forkClass_forkNodeTestcbaC));
	cF_forkNodeTest_forkClass_forkNodeTestcbaB_forkNodeTest_forkClass_forkNodeTestcbaC_guard_LiteralBoolean_CF_forkNodeTest_forkClass_forkNodeTestcbaB_forkNodeTest_forkClass_forkNodeTestcbaC->setValue(true);

	cF_forkNodeTest_forkClass_forkNodeTestcbaB_forkNodeTest_forkClass_forkNodeTestcbaC_weight_LiteralInteger_CF_forkNodeTest_forkClass_forkNodeTestcbaB_forkNodeTest_forkClass_forkNodeTestcbaC = factory->createLiteralInteger_in_Namespace(std::dynamic_pointer_cast<uml::Namespace>(cF_forkNodeTest_forkClass_forkNodeTestcbaB_forkNodeTest_forkClass_forkNodeTestcbaC));
	cF_forkNodeTest_forkClass_forkNodeTestcbaB_forkNodeTest_forkClass_forkNodeTestcbaC_weight_LiteralInteger_CF_forkNodeTest_forkClass_forkNodeTestcbaB_forkNodeTest_forkClass_forkNodeTestcbaC->setValue(0);

	cF_forkNodeTest_forkClass_forkNodeTestcbaC_forkNodeTest_forkClass_forkNodeTestcbaD_guard_LiteralBoolean_CF_forkNodeTest_forkClass_forkNodeTestcbaC_forkNodeTest_forkClass_forkNodeTestcbaD = factory->createLiteralBoolean_in_Namespace(std::dynamic_pointer_cast<uml::Namespace>(cF_forkNodeTest_forkClass_forkNodeTestcbaC_forkNodeTest_forkClass_forkNodeTestcbaD));
	cF_forkNodeTest_forkClass_forkNodeTestcbaC_forkNodeTest_forkClass_forkNodeTestcbaD_guard_LiteralBoolean_CF_forkNodeTest_forkClass_forkNodeTestcbaC_forkNodeTest_forkClass_forkNodeTestcbaD->setValue(true);

	cF_forkNodeTest_forkClass_forkNodeTestcbaC_forkNodeTest_forkClass_forkNodeTestcbaD_weight_LiteralInteger_CF_forkNodeTest_forkClass_forkNodeTestcbaC_forkNodeTest_forkClass_forkNodeTestcbaD = factory->createLiteralInteger_in_Namespace(std::dynamic_pointer_cast<uml::Namespace>(cF_forkNodeTest_forkClass_forkNodeTestcbaC_forkNodeTest_forkClass_forkNodeTestcbaD));
	cF_forkNodeTest_forkClass_forkNodeTestcbaC_forkNodeTest_forkClass_forkNodeTestcbaD_weight_LiteralInteger_CF_forkNodeTest_forkClass_forkNodeTestcbaC_forkNodeTest_forkClass_forkNodeTestcbaD->setValue(0);

	cF_forkNodeTest_forkClass_forkNodeTestcbaD_forkNodeTest_forkClass_forkNodeTestActivityFinal2_guard_LiteralBoolean_CF_forkNodeTest_forkClass_forkNodeTestcbaD_forkNodeTest_forkClass_forkNodeTestActivityFinal2 = factory->createLiteralBoolean_in_Namespace(std::dynamic_pointer_cast<uml::Namespace>(cF_forkNodeTest_forkClass_forkNodeTestcbaD_forkNodeTest_forkClass_forkNodeTestActivityFinal2));
	cF_forkNodeTest_forkClass_forkNodeTestcbaD_forkNodeTest_forkClass_forkNodeTestActivityFinal2_guard_LiteralBoolean_CF_forkNodeTest_forkClass_forkNodeTestcbaD_forkNodeTest_forkClass_forkNodeTestActivityFinal2->setValue(true);

	cF_forkNodeTest_forkClass_forkNodeTestcbaD_forkNodeTest_forkClass_forkNodeTestActivityFinal2_weight_LiteralInteger_CF_forkNodeTest_forkClass_forkNodeTestcbaD_forkNodeTest_forkClass_forkNodeTestActivityFinal2 = factory->createLiteralInteger_in_Namespace(std::dynamic_pointer_cast<uml::Namespace>(cF_forkNodeTest_forkClass_forkNodeTestcbaD_forkNodeTest_forkClass_forkNodeTestActivityFinal2));
	cF_forkNodeTest_forkClass_forkNodeTestcbaD_forkNodeTest_forkClass_forkNodeTestActivityFinal2_weight_LiteralInteger_CF_forkNodeTest_forkClass_forkNodeTestcbaD_forkNodeTest_forkClass_forkNodeTestActivityFinal2->setValue(0);

	cF_forkNodeTest_forkClass_forkNodeTestcbaE_forkNodeTest_forkClass_forkNodeTestcbaF_guard_LiteralBoolean_CF_forkNodeTest_forkClass_forkNodeTestcbaE_forkNodeTest_forkClass_forkNodeTestcbaF = factory->createLiteralBoolean_in_Namespace(std::dynamic_pointer_cast<uml::Namespace>(cF_forkNodeTest_forkClass_forkNodeTestcbaE_forkNodeTest_forkClass_forkNodeTestcbaF));
	cF_forkNodeTest_forkClass_forkNodeTestcbaE_forkNodeTest_forkClass_forkNodeTestcbaF_guard_LiteralBoolean_CF_forkNodeTest_forkClass_forkNodeTestcbaE_forkNodeTest_forkClass_forkNodeTestcbaF->setValue(true);

	cF_forkNodeTest_forkClass_forkNodeTestcbaE_forkNodeTest_forkClass_forkNodeTestcbaF_weight_LiteralInteger_CF_forkNodeTest_forkClass_forkNodeTestcbaE_forkNodeTest_forkClass_forkNodeTestcbaF = factory->createLiteralInteger_in_Namespace(std::dynamic_pointer_cast<uml::Namespace>(cF_forkNodeTest_forkClass_forkNodeTestcbaE_forkNodeTest_forkClass_forkNodeTestcbaF));
	cF_forkNodeTest_forkClass_forkNodeTestcbaE_forkNodeTest_forkClass_forkNodeTestcbaF_weight_LiteralInteger_CF_forkNodeTest_forkClass_forkNodeTestcbaE_forkNodeTest_forkClass_forkNodeTestcbaF->setValue(0);

	cF_forkNodeTest_forkClass_forkNodeTestcbaF_forkNodeTest_forkClass_forkNodeTestcbaG_guard_LiteralBoolean_CF_forkNodeTest_forkClass_forkNodeTestcbaF_forkNodeTest_forkClass_forkNodeTestcbaG = factory->createLiteralBoolean_in_Namespace(std::dynamic_pointer_cast<uml::Namespace>(cF_forkNodeTest_forkClass_forkNodeTestcbaF_forkNodeTest_forkClass_forkNodeTestcbaG));
	cF_forkNodeTest_forkClass_forkNodeTestcbaF_forkNodeTest_forkClass_forkNodeTestcbaG_guard_LiteralBoolean_CF_forkNodeTest_forkClass_forkNodeTestcbaF_forkNodeTest_forkClass_forkNodeTestcbaG->setValue(true);

	cF_forkNodeTest_forkClass_forkNodeTestcbaF_forkNodeTest_forkClass_forkNodeTestcbaG_weight_LiteralInteger_CF_forkNodeTest_forkClass_forkNodeTestcbaF_forkNodeTest_forkClass_forkNodeTestcbaG = factory->createLiteralInteger_in_Namespace(std::dynamic_pointer_cast<uml::Namespace>(cF_forkNodeTest_forkClass_forkNodeTestcbaF_forkNodeTest_forkClass_forkNodeTestcbaG));
	cF_forkNodeTest_forkClass_forkNodeTestcbaF_forkNodeTest_forkClass_forkNodeTestcbaG_weight_LiteralInteger_CF_forkNodeTest_forkClass_forkNodeTestcbaF_forkNodeTest_forkClass_forkNodeTestcbaG->setValue(0);

	cF_forkNodeTest_forkClass_forkNodeTestcbaG_forkNodeTest_forkClass_forkNodeTestcbaH_guard_LiteralBoolean_CF_forkNodeTest_forkClass_forkNodeTestcbaG_forkNodeTest_forkClass_forkNodeTestcbaH = factory->createLiteralBoolean_in_Namespace(std::dynamic_pointer_cast<uml::Namespace>(cF_forkNodeTest_forkClass_forkNodeTestcbaG_forkNodeTest_forkClass_forkNodeTestcbaH));
	cF_forkNodeTest_forkClass_forkNodeTestcbaG_forkNodeTest_forkClass_forkNodeTestcbaH_guard_LiteralBoolean_CF_forkNodeTest_forkClass_forkNodeTestcbaG_forkNodeTest_forkClass_forkNodeTestcbaH->setValue(true);

	cF_forkNodeTest_forkClass_forkNodeTestcbaG_forkNodeTest_forkClass_forkNodeTestcbaH_weight_LiteralInteger_CF_forkNodeTest_forkClass_forkNodeTestcbaG_forkNodeTest_forkClass_forkNodeTestcbaH = factory->createLiteralInteger_in_Namespace(std::dynamic_pointer_cast<uml::Namespace>(cF_forkNodeTest_forkClass_forkNodeTestcbaG_forkNodeTest_forkClass_forkNodeTestcbaH));
	cF_forkNodeTest_forkClass_forkNodeTestcbaG_forkNodeTest_forkClass_forkNodeTestcbaH_weight_LiteralInteger_CF_forkNodeTest_forkClass_forkNodeTestcbaG_forkNodeTest_forkClass_forkNodeTestcbaH->setValue(0);

	cF_forkNodeTest_forkClass_forkNodeTestcbaH_forkNodeTest_forkClass_forkNodeTestcbaL_guard_LiteralBoolean_CF_forkNodeTest_forkClass_forkNodeTestcbaH_forkNodeTest_forkClass_forkNodeTestcbaL = factory->createLiteralBoolean_in_Namespace(std::dynamic_pointer_cast<uml::Namespace>(cF_forkNodeTest_forkClass_forkNodeTestcbaH_forkNodeTest_forkClass_forkNodeTestcbaL));
	cF_forkNodeTest_forkClass_forkNodeTestcbaH_forkNodeTest_forkClass_forkNodeTestcbaL_guard_LiteralBoolean_CF_forkNodeTest_forkClass_forkNodeTestcbaH_forkNodeTest_forkClass_forkNodeTestcbaL->setValue(true);

	cF_forkNodeTest_forkClass_forkNodeTestcbaH_forkNodeTest_forkClass_forkNodeTestcbaL_weight_LiteralInteger_CF_forkNodeTest_forkClass_forkNodeTestcbaH_forkNodeTest_forkClass_forkNodeTestcbaL = factory->createLiteralInteger_in_Namespace(std::dynamic_pointer_cast<uml::Namespace>(cF_forkNodeTest_forkClass_forkNodeTestcbaH_forkNodeTest_forkClass_forkNodeTestcbaL));
	cF_forkNodeTest_forkClass_forkNodeTestcbaH_forkNodeTest_forkClass_forkNodeTestcbaL_weight_LiteralInteger_CF_forkNodeTest_forkClass_forkNodeTestcbaH_forkNodeTest_forkClass_forkNodeTestcbaL->setValue(0);

	cF_forkNodeTest_forkClass_forkNodeTestcbaI_forkNodeTest_forkClass_forkNodeTestcbaJ_guard_LiteralBoolean_CF_forkNodeTest_forkClass_forkNodeTestcbaI_forkNodeTest_forkClass_forkNodeTestcbaJ = factory->createLiteralBoolean_in_Namespace(std::dynamic_pointer_cast<uml::Namespace>(cF_forkNodeTest_forkClass_forkNodeTestcbaI_forkNodeTest_forkClass_forkNodeTestcbaJ));
	cF_forkNodeTest_forkClass_forkNodeTestcbaI_forkNodeTest_forkClass_forkNodeTestcbaJ_guard_LiteralBoolean_CF_forkNodeTest_forkClass_forkNodeTestcbaI_forkNodeTest_forkClass_forkNodeTestcbaJ->setValue(true);

	cF_forkNodeTest_forkClass_forkNodeTestcbaI_forkNodeTest_forkClass_forkNodeTestcbaJ_weight_LiteralInteger_CF_forkNodeTest_forkClass_forkNodeTestcbaI_forkNodeTest_forkClass_forkNodeTestcbaJ = factory->createLiteralInteger_in_Namespace(std::dynamic_pointer_cast<uml::Namespace>(cF_forkNodeTest_forkClass_forkNodeTestcbaI_forkNodeTest_forkClass_forkNodeTestcbaJ));
	cF_forkNodeTest_forkClass_forkNodeTestcbaI_forkNodeTest_forkClass_forkNodeTestcbaJ_weight_LiteralInteger_CF_forkNodeTest_forkClass_forkNodeTestcbaI_forkNodeTest_forkClass_forkNodeTestcbaJ->setValue(0);

	cF_forkNodeTest_forkClass_forkNodeTestcbaJ_forkNodeTest_forkClass_forkNodeTestcbaF_guard_LiteralBoolean_CF_forkNodeTest_forkClass_forkNodeTestcbaJ_forkNodeTest_forkClass_forkNodeTestcbaF = factory->createLiteralBoolean_in_Namespace(std::dynamic_pointer_cast<uml::Namespace>(cF_forkNodeTest_forkClass_forkNodeTestcbaJ_forkNodeTest_forkClass_forkNodeTestcbaF));
	cF_forkNodeTest_forkClass_forkNodeTestcbaJ_forkNodeTest_forkClass_forkNodeTestcbaF_guard_LiteralBoolean_CF_forkNodeTest_forkClass_forkNodeTestcbaJ_forkNodeTest_forkClass_forkNodeTestcbaF->setValue(true);

	cF_forkNodeTest_forkClass_forkNodeTestcbaJ_forkNodeTest_forkClass_forkNodeTestcbaF_weight_LiteralInteger_CF_forkNodeTest_forkClass_forkNodeTestcbaJ_forkNodeTest_forkClass_forkNodeTestcbaF = factory->createLiteralInteger_in_Namespace(std::dynamic_pointer_cast<uml::Namespace>(cF_forkNodeTest_forkClass_forkNodeTestcbaJ_forkNodeTest_forkClass_forkNodeTestcbaF));
	cF_forkNodeTest_forkClass_forkNodeTestcbaJ_forkNodeTest_forkClass_forkNodeTestcbaF_weight_LiteralInteger_CF_forkNodeTest_forkClass_forkNodeTestcbaJ_forkNodeTest_forkClass_forkNodeTestcbaF->setValue(0);

	cF_forkNodeTest_forkClass_forkNodeTestcbaJ_forkNodeTest_forkClass_forkNodeTestcbaK_guard_LiteralBoolean_CF_forkNodeTest_forkClass_forkNodeTestcbaJ_forkNodeTest_forkClass_forkNodeTestcbaK = factory->createLiteralBoolean_in_Namespace(std::dynamic_pointer_cast<uml::Namespace>(cF_forkNodeTest_forkClass_forkNodeTestcbaJ_forkNodeTest_forkClass_forkNodeTestcbaK));
	cF_forkNodeTest_forkClass_forkNodeTestcbaJ_forkNodeTest_forkClass_forkNodeTestcbaK_guard_LiteralBoolean_CF_forkNodeTest_forkClass_forkNodeTestcbaJ_forkNodeTest_forkClass_forkNodeTestcbaK->setValue(true);

	cF_forkNodeTest_forkClass_forkNodeTestcbaJ_forkNodeTest_forkClass_forkNodeTestcbaK_weight_LiteralInteger_CF_forkNodeTest_forkClass_forkNodeTestcbaJ_forkNodeTest_forkClass_forkNodeTestcbaK = factory->createLiteralInteger_in_Namespace(std::dynamic_pointer_cast<uml::Namespace>(cF_forkNodeTest_forkClass_forkNodeTestcbaJ_forkNodeTest_forkClass_forkNodeTestcbaK));
	cF_forkNodeTest_forkClass_forkNodeTestcbaJ_forkNodeTest_forkClass_forkNodeTestcbaK_weight_LiteralInteger_CF_forkNodeTest_forkClass_forkNodeTestcbaJ_forkNodeTest_forkClass_forkNodeTestcbaK->setValue(0);

	cF_forkNodeTest_forkClass_forkNodeTestcbaK_forkNodeTest_forkClass_forkNodeTestcbaL_guard_LiteralBoolean_CF_forkNodeTest_forkClass_forkNodeTestcbaK_forkNodeTest_forkClass_forkNodeTestcbaL = factory->createLiteralBoolean_in_Namespace(std::dynamic_pointer_cast<uml::Namespace>(cF_forkNodeTest_forkClass_forkNodeTestcbaK_forkNodeTest_forkClass_forkNodeTestcbaL));
	cF_forkNodeTest_forkClass_forkNodeTestcbaK_forkNodeTest_forkClass_forkNodeTestcbaL_guard_LiteralBoolean_CF_forkNodeTest_forkClass_forkNodeTestcbaK_forkNodeTest_forkClass_forkNodeTestcbaL->setValue(true);

	cF_forkNodeTest_forkClass_forkNodeTestcbaK_forkNodeTest_forkClass_forkNodeTestcbaL_weight_LiteralInteger_CF_forkNodeTest_forkClass_forkNodeTestcbaK_forkNodeTest_forkClass_forkNodeTestcbaL = factory->createLiteralInteger_in_Namespace(std::dynamic_pointer_cast<uml::Namespace>(cF_forkNodeTest_forkClass_forkNodeTestcbaK_forkNodeTest_forkClass_forkNodeTestcbaL));
	cF_forkNodeTest_forkClass_forkNodeTestcbaK_forkNodeTest_forkClass_forkNodeTestcbaL_weight_LiteralInteger_CF_forkNodeTest_forkClass_forkNodeTestcbaK_forkNodeTest_forkClass_forkNodeTestcbaL->setValue(0);

	cF_forkNodeTest_forkClass_forkNodeTestcbaL_forkNodeTest_forkClass_forkNodeTestActivityFinal1_guard_LiteralBoolean_CF_forkNodeTest_forkClass_forkNodeTestcbaL_forkNodeTest_forkClass_forkNodeTestActivityFinal1 = factory->createLiteralBoolean_in_Namespace(std::dynamic_pointer_cast<uml::Namespace>(cF_forkNodeTest_forkClass_forkNodeTestcbaL_forkNodeTest_forkClass_forkNodeTestActivityFinal1));
	cF_forkNodeTest_forkClass_forkNodeTestcbaL_forkNodeTest_forkClass_forkNodeTestActivityFinal1_guard_LiteralBoolean_CF_forkNodeTest_forkClass_forkNodeTestcbaL_forkNodeTest_forkClass_forkNodeTestActivityFinal1->setValue(true);

	cF_forkNodeTest_forkClass_forkNodeTestcbaL_forkNodeTest_forkClass_forkNodeTestActivityFinal1_weight_LiteralInteger_CF_forkNodeTest_forkClass_forkNodeTestcbaL_forkNodeTest_forkClass_forkNodeTestActivityFinal1 = factory->createLiteralInteger_in_Namespace(std::dynamic_pointer_cast<uml::Namespace>(cF_forkNodeTest_forkClass_forkNodeTestcbaL_forkNodeTest_forkClass_forkNodeTestActivityFinal1));
	cF_forkNodeTest_forkClass_forkNodeTestcbaL_forkNodeTest_forkClass_forkNodeTestActivityFinal1_weight_LiteralInteger_CF_forkNodeTest_forkClass_forkNodeTestcbaL_forkNodeTest_forkClass_forkNodeTestActivityFinal1->setValue(0);
}

void ForkNodeTestPackageImpl::initializePackageContents(std::shared_ptr<uml::Package> forkNodeTest)
{
	if (isInitialized)
	{
		return;
	}
	isInitialized = true;

	// Initialize package
	setName(eNAME);
	setURI(eNS_URI);

	initializePackageActivities();
	initializePackageClasses();
	initializePackageDependencies();
	initializePackageInstanceSpecifications();
	initializePackageInterfaceRealizations();
	initializePackageInterfaces();
	initializePackageStereotypes();
	initializePackageValueSpecifications();

	
}

//ActivityNodes and Edges
void ForkNodeTestPackageImpl::initializePackageActivities()
{
	// activity forkNodeTest
	forkNodeTest_forkClass_forkNodeTest->setName("forkNodeTest");
	
	
	
	
	
	
	forkNodeTest_forkClass_forkNodeTestcbaA->setBehavior(forkNodeTest::ForkNodeTestPackage::eInstance()->get_forkNodeTest_forkClass_fbNull());
	
	
	
	forkNodeTest_forkClass_forkNodeTestcbaB->setBehavior(forkNodeTest::ForkNodeTestPackage::eInstance()->get_forkNodeTest_forkClass_fbNull());
	
	
	
	forkNodeTest_forkClass_forkNodeTestcbaC->setBehavior(forkNodeTest::ForkNodeTestPackage::eInstance()->get_forkNodeTest_forkClass_fbNull());
	
	
	
	forkNodeTest_forkClass_forkNodeTestcbaD->setBehavior(forkNodeTest::ForkNodeTestPackage::eInstance()->get_forkNodeTest_forkClass_fbNull());
	
	
	
	forkNodeTest_forkClass_forkNodeTestcbaE->setBehavior(forkNodeTest::ForkNodeTestPackage::eInstance()->get_forkNodeTest_forkClass_fbNull());
	
	
	
	forkNodeTest_forkClass_forkNodeTestcbaF->setBehavior(forkNodeTest::ForkNodeTestPackage::eInstance()->get_forkNodeTest_forkClass_fbNull());
	
	
	
	forkNodeTest_forkClass_forkNodeTestcbaG->setBehavior(forkNodeTest::ForkNodeTestPackage::eInstance()->get_forkNodeTest_forkClass_fbNull());
	
	
	
	forkNodeTest_forkClass_forkNodeTestcbaH->setBehavior(forkNodeTest::ForkNodeTestPackage::eInstance()->get_forkNodeTest_forkClass_fbNull());
	
	
	
	forkNodeTest_forkClass_forkNodeTestcbaI->setBehavior(forkNodeTest::ForkNodeTestPackage::eInstance()->get_forkNodeTest_forkClass_fbNull());
	
	
	
	forkNodeTest_forkClass_forkNodeTestcbaJ->setBehavior(forkNodeTest::ForkNodeTestPackage::eInstance()->get_forkNodeTest_forkClass_fbNull());
	
	
	
	forkNodeTest_forkClass_forkNodeTestcbaK->setBehavior(forkNodeTest::ForkNodeTestPackage::eInstance()->get_forkNodeTest_forkClass_fbNull());
	
	
	
	forkNodeTest_forkClass_forkNodeTestcbaL->setBehavior(forkNodeTest::ForkNodeTestPackage::eInstance()->get_forkNodeTest_forkClass_fbNull());
	
	
	
	
	cF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaA->setSource(forkNodeTest_forkClass_forkNodeTestFork1);
	forkNodeTest_forkClass_forkNodeTestFork1->getOutgoing()->push_back(cF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaA);
	cF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaA->setTarget(forkNodeTest_forkClass_forkNodeTestcbaA);
	forkNodeTest_forkClass_forkNodeTestcbaA->getIncoming()->push_back(cF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaA);
	cF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaA->setGuard(cF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaA_guard_LiteralBoolean_CF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaA);
	cF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaE->setSource(forkNodeTest_forkClass_forkNodeTestFork1);
	forkNodeTest_forkClass_forkNodeTestFork1->getOutgoing()->push_back(cF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaE);
	cF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaE->setTarget(forkNodeTest_forkClass_forkNodeTestcbaE);
	forkNodeTest_forkClass_forkNodeTestcbaE->getIncoming()->push_back(cF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaE);
	cF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaE->setGuard(cF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaE_guard_LiteralBoolean_CF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaE);
	cF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaI->setSource(forkNodeTest_forkClass_forkNodeTestFork1);
	forkNodeTest_forkClass_forkNodeTestFork1->getOutgoing()->push_back(cF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaI);
	cF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaI->setTarget(forkNodeTest_forkClass_forkNodeTestcbaI);
	forkNodeTest_forkClass_forkNodeTestcbaI->getIncoming()->push_back(cF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaI);
	cF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaI->setGuard(cF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaI_guard_LiteralBoolean_CF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaI);
	cF_forkNodeTest_forkClass_forkNodeTestInitial1_forkNodeTest_forkClass_forkNodeTestFork1->setSource(forkNodeTest_forkClass_forkNodeTestInitial1);
	forkNodeTest_forkClass_forkNodeTestInitial1->getOutgoing()->push_back(cF_forkNodeTest_forkClass_forkNodeTestInitial1_forkNodeTest_forkClass_forkNodeTestFork1);
	cF_forkNodeTest_forkClass_forkNodeTestInitial1_forkNodeTest_forkClass_forkNodeTestFork1->setTarget(forkNodeTest_forkClass_forkNodeTestFork1);
	forkNodeTest_forkClass_forkNodeTestFork1->getIncoming()->push_back(cF_forkNodeTest_forkClass_forkNodeTestInitial1_forkNodeTest_forkClass_forkNodeTestFork1);
	cF_forkNodeTest_forkClass_forkNodeTestInitial1_forkNodeTest_forkClass_forkNodeTestFork1->setGuard(cF_forkNodeTest_forkClass_forkNodeTestInitial1_forkNodeTest_forkClass_forkNodeTestFork1_guard_LiteralBoolean_CF_forkNodeTest_forkClass_forkNodeTestInitial1_forkNodeTest_forkClass_forkNodeTestFork1);
	cF_forkNodeTest_forkClass_forkNodeTestcbaA_forkNodeTest_forkClass_forkNodeTestcbaB->setSource(forkNodeTest_forkClass_forkNodeTestcbaA);
	forkNodeTest_forkClass_forkNodeTestcbaA->getOutgoing()->push_back(cF_forkNodeTest_forkClass_forkNodeTestcbaA_forkNodeTest_forkClass_forkNodeTestcbaB);
	cF_forkNodeTest_forkClass_forkNodeTestcbaA_forkNodeTest_forkClass_forkNodeTestcbaB->setTarget(forkNodeTest_forkClass_forkNodeTestcbaB);
	forkNodeTest_forkClass_forkNodeTestcbaB->getIncoming()->push_back(cF_forkNodeTest_forkClass_forkNodeTestcbaA_forkNodeTest_forkClass_forkNodeTestcbaB);
	cF_forkNodeTest_forkClass_forkNodeTestcbaA_forkNodeTest_forkClass_forkNodeTestcbaB->setGuard(cF_forkNodeTest_forkClass_forkNodeTestcbaA_forkNodeTest_forkClass_forkNodeTestcbaB_guard_LiteralBoolean_CF_forkNodeTest_forkClass_forkNodeTestcbaA_forkNodeTest_forkClass_forkNodeTestcbaB);
	cF_forkNodeTest_forkClass_forkNodeTestcbaB_forkNodeTest_forkClass_forkNodeTestcbaC->setSource(forkNodeTest_forkClass_forkNodeTestcbaB);
	forkNodeTest_forkClass_forkNodeTestcbaB->getOutgoing()->push_back(cF_forkNodeTest_forkClass_forkNodeTestcbaB_forkNodeTest_forkClass_forkNodeTestcbaC);
	cF_forkNodeTest_forkClass_forkNodeTestcbaB_forkNodeTest_forkClass_forkNodeTestcbaC->setTarget(forkNodeTest_forkClass_forkNodeTestcbaC);
	forkNodeTest_forkClass_forkNodeTestcbaC->getIncoming()->push_back(cF_forkNodeTest_forkClass_forkNodeTestcbaB_forkNodeTest_forkClass_forkNodeTestcbaC);
	cF_forkNodeTest_forkClass_forkNodeTestcbaB_forkNodeTest_forkClass_forkNodeTestcbaC->setGuard(cF_forkNodeTest_forkClass_forkNodeTestcbaB_forkNodeTest_forkClass_forkNodeTestcbaC_guard_LiteralBoolean_CF_forkNodeTest_forkClass_forkNodeTestcbaB_forkNodeTest_forkClass_forkNodeTestcbaC);
	cF_forkNodeTest_forkClass_forkNodeTestcbaC_forkNodeTest_forkClass_forkNodeTestcbaD->setSource(forkNodeTest_forkClass_forkNodeTestcbaC);
	forkNodeTest_forkClass_forkNodeTestcbaC->getOutgoing()->push_back(cF_forkNodeTest_forkClass_forkNodeTestcbaC_forkNodeTest_forkClass_forkNodeTestcbaD);
	cF_forkNodeTest_forkClass_forkNodeTestcbaC_forkNodeTest_forkClass_forkNodeTestcbaD->setTarget(forkNodeTest_forkClass_forkNodeTestcbaD);
	forkNodeTest_forkClass_forkNodeTestcbaD->getIncoming()->push_back(cF_forkNodeTest_forkClass_forkNodeTestcbaC_forkNodeTest_forkClass_forkNodeTestcbaD);
	cF_forkNodeTest_forkClass_forkNodeTestcbaC_forkNodeTest_forkClass_forkNodeTestcbaD->setGuard(cF_forkNodeTest_forkClass_forkNodeTestcbaC_forkNodeTest_forkClass_forkNodeTestcbaD_guard_LiteralBoolean_CF_forkNodeTest_forkClass_forkNodeTestcbaC_forkNodeTest_forkClass_forkNodeTestcbaD);
	cF_forkNodeTest_forkClass_forkNodeTestcbaD_forkNodeTest_forkClass_forkNodeTestActivityFinal2->setSource(forkNodeTest_forkClass_forkNodeTestcbaD);
	forkNodeTest_forkClass_forkNodeTestcbaD->getOutgoing()->push_back(cF_forkNodeTest_forkClass_forkNodeTestcbaD_forkNodeTest_forkClass_forkNodeTestActivityFinal2);
	cF_forkNodeTest_forkClass_forkNodeTestcbaD_forkNodeTest_forkClass_forkNodeTestActivityFinal2->setTarget(forkNodeTest_forkClass_forkNodeTestActivityFinal2);
	forkNodeTest_forkClass_forkNodeTestActivityFinal2->getIncoming()->push_back(cF_forkNodeTest_forkClass_forkNodeTestcbaD_forkNodeTest_forkClass_forkNodeTestActivityFinal2);
	cF_forkNodeTest_forkClass_forkNodeTestcbaD_forkNodeTest_forkClass_forkNodeTestActivityFinal2->setGuard(cF_forkNodeTest_forkClass_forkNodeTestcbaD_forkNodeTest_forkClass_forkNodeTestActivityFinal2_guard_LiteralBoolean_CF_forkNodeTest_forkClass_forkNodeTestcbaD_forkNodeTest_forkClass_forkNodeTestActivityFinal2);
	cF_forkNodeTest_forkClass_forkNodeTestcbaE_forkNodeTest_forkClass_forkNodeTestcbaF->setSource(forkNodeTest_forkClass_forkNodeTestcbaE);
	forkNodeTest_forkClass_forkNodeTestcbaE->getOutgoing()->push_back(cF_forkNodeTest_forkClass_forkNodeTestcbaE_forkNodeTest_forkClass_forkNodeTestcbaF);
	cF_forkNodeTest_forkClass_forkNodeTestcbaE_forkNodeTest_forkClass_forkNodeTestcbaF->setTarget(forkNodeTest_forkClass_forkNodeTestcbaF);
	forkNodeTest_forkClass_forkNodeTestcbaF->getIncoming()->push_back(cF_forkNodeTest_forkClass_forkNodeTestcbaE_forkNodeTest_forkClass_forkNodeTestcbaF);
	cF_forkNodeTest_forkClass_forkNodeTestcbaE_forkNodeTest_forkClass_forkNodeTestcbaF->setGuard(cF_forkNodeTest_forkClass_forkNodeTestcbaE_forkNodeTest_forkClass_forkNodeTestcbaF_guard_LiteralBoolean_CF_forkNodeTest_forkClass_forkNodeTestcbaE_forkNodeTest_forkClass_forkNodeTestcbaF);
	cF_forkNodeTest_forkClass_forkNodeTestcbaF_forkNodeTest_forkClass_forkNodeTestcbaG->setSource(forkNodeTest_forkClass_forkNodeTestcbaF);
	forkNodeTest_forkClass_forkNodeTestcbaF->getOutgoing()->push_back(cF_forkNodeTest_forkClass_forkNodeTestcbaF_forkNodeTest_forkClass_forkNodeTestcbaG);
	cF_forkNodeTest_forkClass_forkNodeTestcbaF_forkNodeTest_forkClass_forkNodeTestcbaG->setTarget(forkNodeTest_forkClass_forkNodeTestcbaG);
	forkNodeTest_forkClass_forkNodeTestcbaG->getIncoming()->push_back(cF_forkNodeTest_forkClass_forkNodeTestcbaF_forkNodeTest_forkClass_forkNodeTestcbaG);
	cF_forkNodeTest_forkClass_forkNodeTestcbaF_forkNodeTest_forkClass_forkNodeTestcbaG->setGuard(cF_forkNodeTest_forkClass_forkNodeTestcbaF_forkNodeTest_forkClass_forkNodeTestcbaG_guard_LiteralBoolean_CF_forkNodeTest_forkClass_forkNodeTestcbaF_forkNodeTest_forkClass_forkNodeTestcbaG);
	cF_forkNodeTest_forkClass_forkNodeTestcbaG_forkNodeTest_forkClass_forkNodeTestcbaH->setSource(forkNodeTest_forkClass_forkNodeTestcbaG);
	forkNodeTest_forkClass_forkNodeTestcbaG->getOutgoing()->push_back(cF_forkNodeTest_forkClass_forkNodeTestcbaG_forkNodeTest_forkClass_forkNodeTestcbaH);
	cF_forkNodeTest_forkClass_forkNodeTestcbaG_forkNodeTest_forkClass_forkNodeTestcbaH->setTarget(forkNodeTest_forkClass_forkNodeTestcbaH);
	forkNodeTest_forkClass_forkNodeTestcbaH->getIncoming()->push_back(cF_forkNodeTest_forkClass_forkNodeTestcbaG_forkNodeTest_forkClass_forkNodeTestcbaH);
	cF_forkNodeTest_forkClass_forkNodeTestcbaG_forkNodeTest_forkClass_forkNodeTestcbaH->setGuard(cF_forkNodeTest_forkClass_forkNodeTestcbaG_forkNodeTest_forkClass_forkNodeTestcbaH_guard_LiteralBoolean_CF_forkNodeTest_forkClass_forkNodeTestcbaG_forkNodeTest_forkClass_forkNodeTestcbaH);
	cF_forkNodeTest_forkClass_forkNodeTestcbaH_forkNodeTest_forkClass_forkNodeTestcbaL->setSource(forkNodeTest_forkClass_forkNodeTestcbaH);
	forkNodeTest_forkClass_forkNodeTestcbaH->getOutgoing()->push_back(cF_forkNodeTest_forkClass_forkNodeTestcbaH_forkNodeTest_forkClass_forkNodeTestcbaL);
	cF_forkNodeTest_forkClass_forkNodeTestcbaH_forkNodeTest_forkClass_forkNodeTestcbaL->setTarget(forkNodeTest_forkClass_forkNodeTestcbaL);
	forkNodeTest_forkClass_forkNodeTestcbaL->getIncoming()->push_back(cF_forkNodeTest_forkClass_forkNodeTestcbaH_forkNodeTest_forkClass_forkNodeTestcbaL);
	cF_forkNodeTest_forkClass_forkNodeTestcbaH_forkNodeTest_forkClass_forkNodeTestcbaL->setGuard(cF_forkNodeTest_forkClass_forkNodeTestcbaH_forkNodeTest_forkClass_forkNodeTestcbaL_guard_LiteralBoolean_CF_forkNodeTest_forkClass_forkNodeTestcbaH_forkNodeTest_forkClass_forkNodeTestcbaL);
	cF_forkNodeTest_forkClass_forkNodeTestcbaI_forkNodeTest_forkClass_forkNodeTestcbaJ->setSource(forkNodeTest_forkClass_forkNodeTestcbaI);
	forkNodeTest_forkClass_forkNodeTestcbaI->getOutgoing()->push_back(cF_forkNodeTest_forkClass_forkNodeTestcbaI_forkNodeTest_forkClass_forkNodeTestcbaJ);
	cF_forkNodeTest_forkClass_forkNodeTestcbaI_forkNodeTest_forkClass_forkNodeTestcbaJ->setTarget(forkNodeTest_forkClass_forkNodeTestcbaJ);
	forkNodeTest_forkClass_forkNodeTestcbaJ->getIncoming()->push_back(cF_forkNodeTest_forkClass_forkNodeTestcbaI_forkNodeTest_forkClass_forkNodeTestcbaJ);
	cF_forkNodeTest_forkClass_forkNodeTestcbaI_forkNodeTest_forkClass_forkNodeTestcbaJ->setGuard(cF_forkNodeTest_forkClass_forkNodeTestcbaI_forkNodeTest_forkClass_forkNodeTestcbaJ_guard_LiteralBoolean_CF_forkNodeTest_forkClass_forkNodeTestcbaI_forkNodeTest_forkClass_forkNodeTestcbaJ);
	cF_forkNodeTest_forkClass_forkNodeTestcbaJ_forkNodeTest_forkClass_forkNodeTestcbaF->setSource(forkNodeTest_forkClass_forkNodeTestcbaJ);
	forkNodeTest_forkClass_forkNodeTestcbaJ->getOutgoing()->push_back(cF_forkNodeTest_forkClass_forkNodeTestcbaJ_forkNodeTest_forkClass_forkNodeTestcbaF);
	cF_forkNodeTest_forkClass_forkNodeTestcbaJ_forkNodeTest_forkClass_forkNodeTestcbaF->setTarget(forkNodeTest_forkClass_forkNodeTestcbaF);
	forkNodeTest_forkClass_forkNodeTestcbaF->getIncoming()->push_back(cF_forkNodeTest_forkClass_forkNodeTestcbaJ_forkNodeTest_forkClass_forkNodeTestcbaF);
	cF_forkNodeTest_forkClass_forkNodeTestcbaJ_forkNodeTest_forkClass_forkNodeTestcbaF->setGuard(cF_forkNodeTest_forkClass_forkNodeTestcbaJ_forkNodeTest_forkClass_forkNodeTestcbaF_guard_LiteralBoolean_CF_forkNodeTest_forkClass_forkNodeTestcbaJ_forkNodeTest_forkClass_forkNodeTestcbaF);
	cF_forkNodeTest_forkClass_forkNodeTestcbaJ_forkNodeTest_forkClass_forkNodeTestcbaK->setSource(forkNodeTest_forkClass_forkNodeTestcbaJ);
	forkNodeTest_forkClass_forkNodeTestcbaJ->getOutgoing()->push_back(cF_forkNodeTest_forkClass_forkNodeTestcbaJ_forkNodeTest_forkClass_forkNodeTestcbaK);
	cF_forkNodeTest_forkClass_forkNodeTestcbaJ_forkNodeTest_forkClass_forkNodeTestcbaK->setTarget(forkNodeTest_forkClass_forkNodeTestcbaK);
	forkNodeTest_forkClass_forkNodeTestcbaK->getIncoming()->push_back(cF_forkNodeTest_forkClass_forkNodeTestcbaJ_forkNodeTest_forkClass_forkNodeTestcbaK);
	cF_forkNodeTest_forkClass_forkNodeTestcbaJ_forkNodeTest_forkClass_forkNodeTestcbaK->setGuard(cF_forkNodeTest_forkClass_forkNodeTestcbaJ_forkNodeTest_forkClass_forkNodeTestcbaK_guard_LiteralBoolean_CF_forkNodeTest_forkClass_forkNodeTestcbaJ_forkNodeTest_forkClass_forkNodeTestcbaK);
	cF_forkNodeTest_forkClass_forkNodeTestcbaK_forkNodeTest_forkClass_forkNodeTestcbaL->setSource(forkNodeTest_forkClass_forkNodeTestcbaK);
	forkNodeTest_forkClass_forkNodeTestcbaK->getOutgoing()->push_back(cF_forkNodeTest_forkClass_forkNodeTestcbaK_forkNodeTest_forkClass_forkNodeTestcbaL);
	cF_forkNodeTest_forkClass_forkNodeTestcbaK_forkNodeTest_forkClass_forkNodeTestcbaL->setTarget(forkNodeTest_forkClass_forkNodeTestcbaL);
	forkNodeTest_forkClass_forkNodeTestcbaL->getIncoming()->push_back(cF_forkNodeTest_forkClass_forkNodeTestcbaK_forkNodeTest_forkClass_forkNodeTestcbaL);
	cF_forkNodeTest_forkClass_forkNodeTestcbaK_forkNodeTest_forkClass_forkNodeTestcbaL->setGuard(cF_forkNodeTest_forkClass_forkNodeTestcbaK_forkNodeTest_forkClass_forkNodeTestcbaL_guard_LiteralBoolean_CF_forkNodeTest_forkClass_forkNodeTestcbaK_forkNodeTest_forkClass_forkNodeTestcbaL);
	cF_forkNodeTest_forkClass_forkNodeTestcbaL_forkNodeTest_forkClass_forkNodeTestActivityFinal1->setSource(forkNodeTest_forkClass_forkNodeTestcbaL);
	forkNodeTest_forkClass_forkNodeTestcbaL->getOutgoing()->push_back(cF_forkNodeTest_forkClass_forkNodeTestcbaL_forkNodeTest_forkClass_forkNodeTestActivityFinal1);
	cF_forkNodeTest_forkClass_forkNodeTestcbaL_forkNodeTest_forkClass_forkNodeTestActivityFinal1->setTarget(forkNodeTest_forkClass_forkNodeTestActivityFinal1);
	forkNodeTest_forkClass_forkNodeTestActivityFinal1->getIncoming()->push_back(cF_forkNodeTest_forkClass_forkNodeTestcbaL_forkNodeTest_forkClass_forkNodeTestActivityFinal1);
	cF_forkNodeTest_forkClass_forkNodeTestcbaL_forkNodeTest_forkClass_forkNodeTestActivityFinal1->setGuard(cF_forkNodeTest_forkClass_forkNodeTestcbaL_forkNodeTest_forkClass_forkNodeTestActivityFinal1_guard_LiteralBoolean_CF_forkNodeTest_forkClass_forkNodeTestcbaL_forkNodeTest_forkClass_forkNodeTestActivityFinal1);
	
}

void ForkNodeTestPackageImpl::initializePackageClasses()
{
	std::shared_ptr<uml::Generalization> gen = nullptr;

	//	class forkClass
	forkNodeTest_forkClass->setName("forkClass");
	forkNodeTest_forkClass->setIsAbstract(false);
	
    // forkClass function behaviors
	forkNodeTest_forkClass_fbNull->setName("fbNull");
	forkNodeTest_forkClass_fbNull->setContext(forkNodeTest_forkClass);
	

}

void ForkNodeTestPackageImpl::initializePackageDependencies()
{
}

void ForkNodeTestPackageImpl::initializePackageInstanceSpecifications()
{
}


void ForkNodeTestPackageImpl::initializePackageInterfaceRealizations()
{
}

void ForkNodeTestPackageImpl::initializePackageInterfaces()
{
}

void ForkNodeTestPackageImpl::initializePackageStereotypes()
{
}

void ForkNodeTestPackageImpl::initializePackageValueSpecifications()
{
}

std::shared_ptr<uml::ControlFlow> ForkNodeTestPackageImpl::get_CF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaA()
{
	return cF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaA;
}
std::shared_ptr<uml::ControlFlow> ForkNodeTestPackageImpl::get_CF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaE()
{
	return cF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaE;
}
std::shared_ptr<uml::ControlFlow> ForkNodeTestPackageImpl::get_CF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaI()
{
	return cF_forkNodeTest_forkClass_forkNodeTestFork1_forkNodeTest_forkClass_forkNodeTestcbaI;
}
std::shared_ptr<uml::ControlFlow> ForkNodeTestPackageImpl::get_CF_forkNodeTest_forkClass_forkNodeTestInitial1_forkNodeTest_forkClass_forkNodeTestFork1()
{
	return cF_forkNodeTest_forkClass_forkNodeTestInitial1_forkNodeTest_forkClass_forkNodeTestFork1;
}
std::shared_ptr<uml::ControlFlow> ForkNodeTestPackageImpl::get_CF_forkNodeTest_forkClass_forkNodeTestcbaA_forkNodeTest_forkClass_forkNodeTestcbaB()
{
	return cF_forkNodeTest_forkClass_forkNodeTestcbaA_forkNodeTest_forkClass_forkNodeTestcbaB;
}
std::shared_ptr<uml::ControlFlow> ForkNodeTestPackageImpl::get_CF_forkNodeTest_forkClass_forkNodeTestcbaB_forkNodeTest_forkClass_forkNodeTestcbaC()
{
	return cF_forkNodeTest_forkClass_forkNodeTestcbaB_forkNodeTest_forkClass_forkNodeTestcbaC;
}
std::shared_ptr<uml::ControlFlow> ForkNodeTestPackageImpl::get_CF_forkNodeTest_forkClass_forkNodeTestcbaC_forkNodeTest_forkClass_forkNodeTestcbaD()
{
	return cF_forkNodeTest_forkClass_forkNodeTestcbaC_forkNodeTest_forkClass_forkNodeTestcbaD;
}
std::shared_ptr<uml::ControlFlow> ForkNodeTestPackageImpl::get_CF_forkNodeTest_forkClass_forkNodeTestcbaD_forkNodeTest_forkClass_forkNodeTestActivityFinal2()
{
	return cF_forkNodeTest_forkClass_forkNodeTestcbaD_forkNodeTest_forkClass_forkNodeTestActivityFinal2;
}
std::shared_ptr<uml::ControlFlow> ForkNodeTestPackageImpl::get_CF_forkNodeTest_forkClass_forkNodeTestcbaE_forkNodeTest_forkClass_forkNodeTestcbaF()
{
	return cF_forkNodeTest_forkClass_forkNodeTestcbaE_forkNodeTest_forkClass_forkNodeTestcbaF;
}
std::shared_ptr<uml::ControlFlow> ForkNodeTestPackageImpl::get_CF_forkNodeTest_forkClass_forkNodeTestcbaF_forkNodeTest_forkClass_forkNodeTestcbaG()
{
	return cF_forkNodeTest_forkClass_forkNodeTestcbaF_forkNodeTest_forkClass_forkNodeTestcbaG;
}
std::shared_ptr<uml::ControlFlow> ForkNodeTestPackageImpl::get_CF_forkNodeTest_forkClass_forkNodeTestcbaG_forkNodeTest_forkClass_forkNodeTestcbaH()
{
	return cF_forkNodeTest_forkClass_forkNodeTestcbaG_forkNodeTest_forkClass_forkNodeTestcbaH;
}
std::shared_ptr<uml::ControlFlow> ForkNodeTestPackageImpl::get_CF_forkNodeTest_forkClass_forkNodeTestcbaH_forkNodeTest_forkClass_forkNodeTestcbaL()
{
	return cF_forkNodeTest_forkClass_forkNodeTestcbaH_forkNodeTest_forkClass_forkNodeTestcbaL;
}
std::shared_ptr<uml::ControlFlow> ForkNodeTestPackageImpl::get_CF_forkNodeTest_forkClass_forkNodeTestcbaI_forkNodeTest_forkClass_forkNodeTestcbaJ()
{
	return cF_forkNodeTest_forkClass_forkNodeTestcbaI_forkNodeTest_forkClass_forkNodeTestcbaJ;
}
std::shared_ptr<uml::ControlFlow> ForkNodeTestPackageImpl::get_CF_forkNodeTest_forkClass_forkNodeTestcbaJ_forkNodeTest_forkClass_forkNodeTestcbaF()
{
	return cF_forkNodeTest_forkClass_forkNodeTestcbaJ_forkNodeTest_forkClass_forkNodeTestcbaF;
}
std::shared_ptr<uml::ControlFlow> ForkNodeTestPackageImpl::get_CF_forkNodeTest_forkClass_forkNodeTestcbaJ_forkNodeTest_forkClass_forkNodeTestcbaK()
{
	return cF_forkNodeTest_forkClass_forkNodeTestcbaJ_forkNodeTest_forkClass_forkNodeTestcbaK;
}
std::shared_ptr<uml::ControlFlow> ForkNodeTestPackageImpl::get_CF_forkNodeTest_forkClass_forkNodeTestcbaK_forkNodeTest_forkClass_forkNodeTestcbaL()
{
	return cF_forkNodeTest_forkClass_forkNodeTestcbaK_forkNodeTest_forkClass_forkNodeTestcbaL;
}
std::shared_ptr<uml::ControlFlow> ForkNodeTestPackageImpl::get_CF_forkNodeTest_forkClass_forkNodeTestcbaL_forkNodeTest_forkClass_forkNodeTestActivityFinal1()
{
	return cF_forkNodeTest_forkClass_forkNodeTestcbaL_forkNodeTest_forkClass_forkNodeTestActivityFinal1;
}
std::shared_ptr<uml::Class> ForkNodeTestPackageImpl::get_forkNodeTest_forkClass()
{
	return forkNodeTest_forkClass;
}
std::shared_ptr<uml::FunctionBehavior> ForkNodeTestPackageImpl::get_forkNodeTest_forkClass_fbNull()
{
	return forkNodeTest_forkClass_fbNull;
}
std::shared_ptr<uml::Activity> ForkNodeTestPackageImpl::get_forkNodeTest_forkClass_forkNodeTest()
{
	return forkNodeTest_forkClass_forkNodeTest;
}
std::shared_ptr<uml::ActivityFinalNode> ForkNodeTestPackageImpl::get_forkNodeTest_forkClass_forkNodeTestActivityFinal1()
{
	return forkNodeTest_forkClass_forkNodeTestActivityFinal1;
}
std::shared_ptr<uml::ActivityFinalNode> ForkNodeTestPackageImpl::get_forkNodeTest_forkClass_forkNodeTestActivityFinal2()
{
	return forkNodeTest_forkClass_forkNodeTestActivityFinal2;
}
std::shared_ptr<uml::ForkNode> ForkNodeTestPackageImpl::get_forkNodeTest_forkClass_forkNodeTestFork1()
{
	return forkNodeTest_forkClass_forkNodeTestFork1;
}
std::shared_ptr<uml::InitialNode> ForkNodeTestPackageImpl::get_forkNodeTest_forkClass_forkNodeTestInitial1()
{
	return forkNodeTest_forkClass_forkNodeTestInitial1;
}
std::shared_ptr<uml::CallBehaviorAction> ForkNodeTestPackageImpl::get_forkNodeTest_forkClass_forkNodeTestcbaA()
{
	return forkNodeTest_forkClass_forkNodeTestcbaA;
}
std::shared_ptr<uml::CallBehaviorAction> ForkNodeTestPackageImpl::get_forkNodeTest_forkClass_forkNodeTestcbaB()
{
	return forkNodeTest_forkClass_forkNodeTestcbaB;
}
std::shared_ptr<uml::CallBehaviorAction> ForkNodeTestPackageImpl::get_forkNodeTest_forkClass_forkNodeTestcbaC()
{
	return forkNodeTest_forkClass_forkNodeTestcbaC;
}
std::shared_ptr<uml::CallBehaviorAction> ForkNodeTestPackageImpl::get_forkNodeTest_forkClass_forkNodeTestcbaD()
{
	return forkNodeTest_forkClass_forkNodeTestcbaD;
}
std::shared_ptr<uml::CallBehaviorAction> ForkNodeTestPackageImpl::get_forkNodeTest_forkClass_forkNodeTestcbaE()
{
	return forkNodeTest_forkClass_forkNodeTestcbaE;
}
std::shared_ptr<uml::CallBehaviorAction> ForkNodeTestPackageImpl::get_forkNodeTest_forkClass_forkNodeTestcbaF()
{
	return forkNodeTest_forkClass_forkNodeTestcbaF;
}
std::shared_ptr<uml::CallBehaviorAction> ForkNodeTestPackageImpl::get_forkNodeTest_forkClass_forkNodeTestcbaG()
{
	return forkNodeTest_forkClass_forkNodeTestcbaG;
}
std::shared_ptr<uml::CallBehaviorAction> ForkNodeTestPackageImpl::get_forkNodeTest_forkClass_forkNodeTestcbaH()
{
	return forkNodeTest_forkClass_forkNodeTestcbaH;
}
std::shared_ptr<uml::CallBehaviorAction> ForkNodeTestPackageImpl::get_forkNodeTest_forkClass_forkNodeTestcbaI()
{
	return forkNodeTest_forkClass_forkNodeTestcbaI;
}
std::shared_ptr<uml::CallBehaviorAction> ForkNodeTestPackageImpl::get_forkNodeTest_forkClass_forkNodeTestcbaJ()
{
	return forkNodeTest_forkClass_forkNodeTestcbaJ;
}
std::shared_ptr<uml::CallBehaviorAction> ForkNodeTestPackageImpl::get_forkNodeTest_forkClass_forkNodeTestcbaK()
{
	return forkNodeTest_forkClass_forkNodeTestcbaK;
}
std::shared_ptr<uml::CallBehaviorAction> ForkNodeTestPackageImpl::get_forkNodeTest_forkClass_forkNodeTestcbaL()
{
	return forkNodeTest_forkClass_forkNodeTestcbaL;
}


