/*
 * MDE4CPP - Model Driven Engineering for C++
 *
 * Copyright (c) TU Ilmenau, Systems and Software Engineering Group
 * All rights reserved.
 *
 * MIT License
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this
 * software and associated documentation files (the "Software"), to deal in the Software
 * without restriction, including without limitation the rights to use, copy, modify, merge,
 * publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons
 * to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or
 * substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED *AS IS*, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
 * PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
 * FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */
plugins{
	id "tui.sse.mde4cpp.MDE4CPPGenerate" version "0.6"	
}

description 'Example collection'

import org.gradle.internal.os.OperatingSystem;

def allPSSMModelExamples = 
[
//	[{Model project directory}, {Model name}, {taskName}]	 
	 ['./PSSM_ComplexBehavior/', 'PSSM_ComplexBehavior', 'generatePSSM_ComplexBehavior']
	,['./PSSM_Composite/', 'PSSM_Composite', 'generatePSSM_Composite']	
	,['./PSSM_HelloWorld/', 'PSSM_HelloWorld', 'generatePSSM_HelloWorld']
	,['./PSSM_InternalTransition/', 'PSSM_InternalTransition', 'generatePSSM_InternalTransition']	
	,['./PSSM_Triggers/', 'PSSM_Triggers', 'generatePSSM_Triggers']
	,['./VendingMachine/', 'VendingMachine', 'generateVendingMachine']
]

def allPSSMTestSuiteModels =
[
//	[{Model project directory}, {Model name}, {taskName}]
	 ['./TestSuite/Test_Behavior_001', 'Test_Behavior_001', 'generateTest_Behavior_001']
]

task generatePSSMModelExamples() {
	group 'Examples'
	description 'generate PSSM Model Examples'	
	
	dependsOn getRootProject().getTasksByName('createAllGenerators', true)

	allPSSMModelExamples.each { model ->

		def buildModelFile = file("${model[0]}/model/build.gradle")
		def buildSrcFile = file("${model[0]}/src_gen/build.gradle")
		if(!(buildModelFile.exists() && buildSrcFile.exists()))
		{
			def generateTask = tasks.create("generate${model[2]}", tui.sse.mde4cpp.MDE4CPPGenerate) 
			{
				modelFilePath = file("${model[0]}/model/${model[1]}.uml")
			}
			dependsOn generateTask
		}
		else
		{	
			def projectPath = model[0].replace('./', '').replaceAll('/$', '')
			def targetProject = findProject(projectPath)			
			if (targetProject != null) 
			{
				dependsOn targetProject.tasks.getByName("generate${model[2]}")
			}
			else
			{
				println "No project found for model: " + projectPath + ":generate${model[2]}"
			}
		}			
	}	
}

task compilePSSMModelExamples() {
	group 'Examples'
	description 'compile applications for PSSM Model Examples'	

	doLast
	{
		def tool = '/bin/sh'
		def command = '-c'

		
		if (System.properties['os.name'].toLowerCase().contains('windows')) {
			tool = 'cmd'
			command = '/C'

		}
		
		allPSSMModelExamples.each { model ->
		// model[0] = model project root directoy, model[1] = model name
			exec
			{
				workingDir = file("${model[0]}")
				commandLine = [tool, command, 'gradlew compileApplicationFor' + model[1]]
			}
		}
	}
}

task buildPSSMModelExamples() 
{
	group 'Examples'
	description 'generate and compile applications for PSSM Model Examples'

	def tasks = [
		generatePSSMModelExamples,
		compilePSSMModelExamples
	]
	
	for (int i = 0; i < tasks.size() - 1; i++) {
        tasks[i + 1].mustRunAfter(tasks[i])
    }
    
    dependsOn(tasks)
}

task generatePSSMTestSuite() {
	group 'Tests'
	description 'generate test suite for PSSMExamples'	
	
	dependsOn getRootProject().getTasksByName('createAllGenerators', true)
	allPSSMTestSuiteModels.each { model ->
		def buildModelFile = file("${model[0]}/model/build.gradle")
		def buildSrcFile = file("${model[0]}/src_gen/build.gradle")
		if(!(buildModelFile.exists() && buildSrcFile.exists()))
		{
			def generateTask = tasks.create("generate${model[2]}", tui.sse.mde4cpp.MDE4CPPGenerate) 
			{
				modelFilePath = file("${model[0]}/model/${model[1]}.uml")
			}
			dependsOn generateTask
		}
		else
		{	
			def projectPath = model[0].replace('./', '').replaceAll('/$', '')
			def targetProject = findProject(projectPath)			
			if (targetProject != null) 
			{
				dependsOn targetProject.tasks.getByName("generate${model[2]}")
			}
			else
			{
				println "No project found for model: " + projectPath + ":generate${model[2]}"
			}
		}	
	}	
}

task compilePSSMTestSuite() {
	group 'Tests'
	description 'compile applications for PSSMExamples test suite'	

	doLast
	{
		def tool = '/bin/sh'
		def command = '-c'

		
		if (System.properties['os.name'].toLowerCase().contains('windows')) {
			tool = 'cmd'
			command = '/C'

		}
		
		allPSSMTestSuiteModels.each { model ->
		// model[0] = model project root directoy, model[1] = model name
			exec
			{
				workingDir = file("${model[0]}")
				commandLine = [tool, command, 'gradlew compileApplicationFor' + model[1]]
			}
		}
	}
}

task buildPSSMTestSuite() 
{
	group 'Tests'
	description 'generate and compile applications for PSSMExamples test suite'

	def tasks = [
		generatePSSMTestSuite,
		compilePSSMTestSuite
	]
	
	for (int i = 0; i < tasks.size() - 1; i++) {
        tasks[i + 1].mustRunAfter(tasks[i])
    }
    
    dependsOn(tasks)
}
